### ISSUE TITLE
Make it possible to write to a file via binding / .write / .append

### ISSUE THREAD

**Issue by holyjak** [borkdude/babashka#103]
Currently I do not see a way to write into a file in bb. In Clojure I'd do one of these

```clojure
(with-open [wrt (io/writer "my/file.txt")]
   (binding [*out* wrt] (println "hi"))
  (.write wrt "hi\n")
  (.append wrt "hi\n")
```

I am trying to change a number of files so writing to bb's stdout and redirecting to file won't help.

however none works in babashka. Or is there another way? Thank you!

**Comment by borkdude** [comment]
What about `(spit file contents :append true)`?
