### ISSUE TITLE
Expose `File.getAbsolutePath`

### ISSUE THREAD

**Issue by holyjak** [borkdude/babashka#104]
I guess this can be quite useful in some cases?

**Comment by borkdude** [comment]
I'm working on a new way to add class support to babashka/sci. See the reflection branch:
https://github.com/borkdude/babashka/compare/reflect
It's probably best to wait for that, because then it will automatically be added.

**Comment by borkdude** [comment]
This now works on master:

```
$ ./bb '(.getAbsolutePath (io/file "."))'
"/Users/borkdude/Dropbox/dev/clojure/babashka/."
```
