### ISSUE TITLE
Expose `java.nio.file.Files` with its static functions such as `move`

### ISSUE THREAD

**Issue by holyjak** [borkdude/babashka#105]
these are superior to what `File` can do and e.g. `move` is more reliable across OSes than `File.renameTo` according to the javadoc.

**Comment by borkdude** [comment]
I'm working on a new way to add class support to babashka/sci. See the reflection branch:
https://github.com/borkdude/babashka/compare/reflect
It's probably best to wait for that, because then it will hopefully be trivial to add.

**Comment by borkdude** [comment]
@holyjak Can you please provide some complete example scripts of what you would like to see supported, that I can execute with `clojure -e script.clj`? Since most of the methods in java.nio.file.Files are variadic I have trouble getting the most basic stuff working.

**Comment by holyjak** [comment]
These two cases are what I needed. It is ugly with variadic methods but that's life :-( (Run the code twice.)

```clojure
(do
    (.createNewFile (io/file "/tmp/f1"))
    (let [p (.toPath (io/file "/tmp/f1"))
          p' (.resolveSibling p "f2")]
        (try
          (java.nio.file.Files/move p p' (into-array java.nio.file.CopyOption []))
          (println "Target file did not exist and move succeeded")
          (catch java.nio.file.FileAlreadyExistsException _
            (println "Target file already exists, going to force it...")
            (java.nio.file.Files/move p p' (into-array [java.nio.file.StandardCopyOption/REPLACE_EXISTING]))))))
```
