### ISSUE TITLE
Error resolving quoted symbols inside try

### ISSUE THREAD

**Issue by mauricioszabo** [borkdude/babashka#117]
On Babashka 0.0.30, on Ubuntu 18.04 (last release) it can't detect quoted symbols inside a `try` block, so the following code fails:

```clojure
(try 'a-symbol)
```

Expected to return `a-symbol`, returns:

```
Could not resolve symbol: a-symbol [at line 1, column 6]
```

**Comment by borkdude** [comment]
Fixed in v0.0.31.
