### ISSUE TITLE
Using field accessors within a (try ...) block gives errors

### ISSUE THREAD

**Issue by jeroenvandijk** [borkdude/babashka#118]
**version**

bb -h
babashka v0.0.30

**platform**

OSX

**problem**

While working with exceptions I came across the issue below. There is something with the `try` macro and accessing java members

**repro**
```
bb -e '(try (throw (ex-info "foo" {})) (catch Exception e (.getMessage e)))'
No matching method g found taking 9 args for class clojure.lang.ExceptionInfo [at line 1, column 52]
```
Or even
```
bb -e '(try (.getMessage (ex-info "foo" {})))'
```
Or just something with `try`
```
bb -e '(try (.toString "foo"))'
No matching method t found taking 7 args for class java.lang.String [at line 1, column 1]
```

**expected behavior**

```
bb -e '(.getMessage (ex-info "foo" {}))'
"foo"
```

**Comment by borkdude** [comment]
Please upgrade to v0.0.31.

**Comment by jeroenvandijk** [comment]
You are right, it's fixed. Hard to keep up with all your releases :)

**Comment by borkdude** [comment]
Sorry for the bug :)
