### ISSUE TITLE
add conch main namespace

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#119]
Most notable the `programs` macro.

**Comment by borkdude** [comment]
This seems to be stuck:

```
$ bb '(conch/programs grep ps) (grep "ssh" {:in (ps "-e" {:seq true})})'
```

**Comment by sogaiu** [comment]
Here on manjaro linux, both invoked with lein and via a native-image build, I get a fair bit of output followed by a pause.

**Comment by borkdude** [comment]
Merged master into the conch branch. Still the same issue:

```
lein bb '(conch/programs grep ps) (type (:out (grep "ssh" {:in (ps "-e" {:seq true})})))'
```
hangs.

**Comment by borkdude** [comment]
It seems a normal JVM also hangs there:

```
clj -Sdeps '{:deps {clj-commons/conch {:mvn/version "RELEASE"}}}' -e "(require '[me.raynes.conch :as conch]) (conch/programs grep ps) (grep \"ssh\" {:in (ps \"-e\" {:seq true})})"
```

**Comment by borkdude** [comment]
See note here: https://github.com/Raynes/conch#hanging

**Comment by borkdude** [comment]
We have dropped support for conch in favour of java.lang.ProcessBuilder.
