### ISSUE TITLE
Error in bb script

### ISSUE THREAD

**Issue by Gavlooth** [borkdude/babashka#124]
I the "Running a file section" the script destructures has keywords instead of symbols:  
  (let [{:keys [:exit :err :out]} (shell/sh "curl" "-sS" url)]  
instead of    
  (let [{:keys [exit err out]} (shell/sh "curl" "-sS" url)]

**Comment by borkdude** [comment]
@Gavlooth That's not an error. Clojure accepts either keywords or symbols in key destructuring.

**Comment by Gavlooth** [comment]
@borkdude ok I really wasn't aware of that. The script fails for some reason when i run it, and the failure is on the same line. Sorry about that

**Comment by borkdude** [comment]
@Gavlooth Can you post a repro of the thing that does not work?
When I copy that script to a file `script.bb` and run:

```
$ bb script.bb https://www.clojure.org /tmp/out.html
```
it works as expected.
