### ISSUE TITLE
Provide known-good SHA sums for the assets

### ISSUE THREAD

**Issue by KaliszAd** [borkdude/babashka#1369]
There are no known good checksums of the assets making automatic checking of consistency difficult.

It is customary for a project to provide a sha256sums.txt or SHA256SUMS e.g. by using `find . -type f -name babashka* -exec sha256sum '{}' \; > sha256sums.txt` or similar incantation making sure the output is `checksum  filename`. This can than be used in scripts with `sha256sum -c <sums-file> 2>&1 | grep OK` or similar.

One example is https://github.com/prometheus/prom2json/releases/latest or https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/ where it is just called SHA256SUMS. Btw. for macOS, there could be SHA1 checksum in a respective shasums.txt using shasums.txt or the script could upgrade to `shasum -a 256` and skip the double effort, duplicate files and deprecated algorithm.

The alternative of downloading those files separately, creating a checksum etc. is bothersome and postpones the checking when many systems have already touched the files and could have introduced inconsistencies. Creating the sums at build time would be most preferable.

**Comment by borkdude** [comment]
I think if we add an option to https://github.com/borkdude/gh-release-artifact to calculate the sha256 sum (in Clojure, so OS-independent) and upload <filemame>.sha256 along with <filename> we can enable this option on every CI and then it would be fully implemented.

**Comment by borkdude** [comment]
Seems to work for dev release, so from the next version on we will have `.sha256` files for every asset:

<img width="878" alt="Screenshot 2022-10-06 at 14 16 59" src="https://user-images.githubusercontent.com/284934/194310368-acedf9a5-923b-4f92-941f-a2154a704f8e.png">

**Comment by KaliszAd** [comment]
I am finally using this in the Ansible role: https://github.com/OrgPad-com/ansible-role-babashka it works on Linux and amd64, with small adaptation, it should work on macOS too.

**Comment by borkdude** [comment]
great!
