### ISSUE TITLE
Consider adding clojure.data.xml

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#153]
This seems to work in the `clojure.data.xml` branch:

```
$ rlwrap ./bb
Babashka v0.0.42-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.
user=> (require '[clojure.data.xml :as xml] )
nil
user=> (xml/parse-str "<item></item>")
#xml/element{:tag :item}
user=> (def xml (xml/parse-str "<item></item>"))
#'user/xml
user=> (xml/emit-str (assoc xml :content [(xml/element :child {})]))
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><item><child/></item>"
```

See https://github.com/oracle/graal/issues/1387

TODO: 

- [x] check with a java11 version of GraalVM if the above works

**Comment by xificurC** [comment]
This would be nice to have, I want to generate an rss feed xml file with the help of bb

**Comment by borkdude** [comment]
@xificurC What about first adding hiccup? This would be useful for HTML generation, but could also help generating XML I guess?

**Comment by xificurC** [comment]
Hmm, I haven't yet thought through whether I'll regenerate the feed everytime or parse it and just adjust it. I guess generating would suffice for now though. My questions:

- is hiccup used for generating xml? Or better, can it be used? I'm not well versed in (x)html and xml to know if there are any quirks that would break when using a library that is primarily inteded for generating html
- what makes you refrain from merging the working xml branch?

**Comment by borkdude** [comment]
> what makes you refrain from merging the working xml branch?

It needs more testing. After the initial attempt I got:

```
Provider com.sun.xml.internal.stream.XMLInputFactoryImpl not found
```

When looking at https://github.com/oracle/graal/issues/1387 I found that adding:

```
{"name":"com.sun.xml.internal.stream.XMLInputFactoryImpl",	
   "methods":[{"name":"<init>","parameterTypes":[] }]},	
  {"name":"com.sun.xml.internal.stream.XMLOutputFactoryImpl",	
   "methods":[{"name":"<init>","parameterTypes":[] }]}
```
to the reflection config, got me a little further. See the above example.

But these classes are com.sun classes and those are generally not stable / public. So it would be better if I should not have to use this workaround.

With the workaround in place, it still needs more testing.

E.g. I just got:
```
user=> (let [xml (xml/parse-str "<items><item>1</item><item>2</item><items>")] (xml/emit-str xml))
Could not load any resource bundle by com.sun.org.apache.xerces.internal.impl.msg.XMLMessages [at line 3, column 73]
```
I'm not sure what the proper solution for that is yet.

There's also the binary size. Adding clojure.data.xml bindings and the stuff to the reflection config added about 2MB to the binary size. This seems small, but I'd rather not make it bigger than necessary.

**Comment by borkdude** [comment]
@xificurC Turned out I made a typo:

```
user=> (require '[clojure.data.xml :as xml])
nil
user=> (let [xml (xml/parse-str "<items><item>1</item><item>2</item></items>")] (xml/emit-str xml))
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><items><item>1</item><item>2</item></items>"
```

GraalVM probably didn't compile the right exception along, that's why I got the strange error message.

If you're interested in testing with these binaries, here are a few links (got them from the babashka_circleci_builds channel on Clojurians slack):

```
[linux - jdk11-clojure.data.xml@14963f65f56069edc59061a366c5fcb9ead07be0]: https://3404-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.61-SNAPSHOT-linux-amd64.zip
[linux - clojure.data.xml@56880b309320ff01889b62df41cdb377aab807e5]: https://3407-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.61-SNAPSHOT-linux-amd64.zip
[macos - clojure.data.xml@56880b309320ff01889b62df41cdb377aab807e5]: https://3408-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.61-SNAPSHOT-macos-amd64.zip
```

**Comment by xificurC** [comment]
I see. 2MB is a lot for just 1 new library. I'd probably be OK with just hiccup, is that somewhere on the radar?

**Comment by borkdude** [comment]
@xificurC Hiccup is on the radar, but I don't know when. Might be worth looking into https://github.com/retrogradeorbit/bootleg as well.

**Comment by borkdude** [comment]
@xificurC Hiccup is on the radar, but I don't know when.

By all means do experiment with one of the builds from above. The more feedback we can get on this, the better it is.

2mb / 0.4mb zipped is not too bad maybe for having the affordances of clojure.data.xml.

Might be worth looking into https://github.com/retrogradeorbit/bootleg as well.

**Comment by xificurC** [comment]
Bootleg [seems to be using](https://github.com/retrogradeorbit/bootleg/blob/a459e2ca398a743c42bb0aac42261117d78d6e7d/src/bootleg/utils.clj#L153) hickory to produce html from hiccup, but this session didn't exactly work:

```
% export BABASHKA_CLASSPATH="$(clojure -Sdeps '{:deps {hickory {:mvn/version "0.7.1"}}}' -Spath)"
% bb
Babashka v0.0.60 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[hickory.core :as h])
Unable to resolve classname: org.jsoup.Jsoup [at hickory/core.clj, line , column ]
hickory.core=>
```

I haven't played around with anything graal-related so I'm just walking in darkness here.

WRT data.xml, if you don't like the workaround I don't see much point in testing it?

**Comment by borkdude** [comment]
@xificurC You can't use arbitrary libraries with babashka, only those who can be interpreted by babashka (which contains a subset of Clojure and a subset of classes from the JVM). 

My bootleg suggestion was more about actually using bootleg itself for your purposes.

The workaround might be OK, until the GraalVM folks have a better one. There is an issue about it (see above).

**Comment by borkdude** [comment]
@xificurC Note that a few simple functions go a long way. E.g. this http server written in babashka produces HTML as follows:

https://github.com/borkdude/babashka/blob/f1eb902f4113b84db22d4b498ecc9975ee65e640/examples/http_server.clj#L22

**Comment by borkdude** [comment]
@xificurC Here is a very simple (probably a little too simple) html function:

```
(ns simple.hiccup
  (:require [clojure.string :as str]))

(defn html [v]
  (cond (vector? v)
        (let [tag (first v)
              attrs (second v)
              attrs (when (map? attrs) attrs)
              elts (if attrs (nnext v) (next v))
              tag-name (name tag)]
          (format "<%s%s>%s</%s>\n" tag-name (html attrs) (html elts) tag-name))
        (map? v)
        (str/join ""
                  (map (fn [[k v]]
                         (format " %s=\"%s\"" (name k) v)) v))
        (seq? v)
        (str/join " " (map html v))
        :else (str v)))

(println
 (html
  [:div
   {:id "app" :class "class1"}
   [:span 1 2 3]
   [:ul [:li 1] [:li 2] [:li 3]]]))
```

Executing this with bb gives:

```
<div id="app" class="class1"><span>1 2 3</span>
 <ul><li>1</li>
 <li>2</li>
 <li>3</li>
</ul>
</div>
```

**Comment by xificurC** [comment]
Duh, you're right, this isn't exactly rocket science. Your example isn't complete hiccup but isn't far from it either. Thanks a lot, I will whip something up and share it afterwards.

**Comment by borkdude** [comment]
From the native-image channel on the GraalVM slack:

![Screenshot 2020-01-16 12 09 34](https://user-images.githubusercontent.com/284934/72520154-1ee83280-3859-11ea-8d66-96f58f457130.png)

**Comment by retrogradeorbit** [comment]
@xificurC I wrote a blog post about generating rss xml with booleg which may give you some ideas here: https://epiccastle.io/blog/generating-xml-with-bootleg/

**Comment by borkdude** [comment]
This is now added in version 0.0.88.

**Comment by sogaiu** [comment]
A bit late to the party, but very happy to see this included :+1:
