### ISSUE TITLE
Record port number of socket repl in an appropriate file

### ISSUE THREAD

**Issue by sogaiu** [borkdude/babashka#157]
**Is your feature request related to a problem? Please describe.**

It can be tedious to have to manually determine and input repl port numbers into tooling.

**Describe the solution you'd like**

Storage of in-use socket repl port numbers into appropriate files.

Appropriately deleting such files is also important so that tooling and users don't get confused.  (For other tools that do this sort of thing, they typically use Java's .deleteOnExit.)

Tooling can then discover which repl ports are currently being used for a given project.

However, see additional notes below concerning location ideas.

**Describe alternatives you've considered**

Boot, shadow-cljs, and nrepl record port information in files somewhere under a given project directory.

It turns out, AFAICT, none of the things I've examined that record the port info seem to account for the case of running more than one process for a given project.  That's something I do.

Clojure's socket repl doesn't use something like the .nrepl-port file in a project directory.  This avoids the issue of overwriting / corrupting the file.

shadow-cljs is the best of the bunch in that at least it makes its own subdirectory to put process-related files in presumably so it doesn't conflict with other tooling.

I think this could happen if you use both boot and leiningen for a project.  This is because they both use nrepl by default, leading to writing to the same .nrepl-port file, IIUC.  I haven't tested this, but I have observed them both creating and deleting a .nrepl-port file.

AFAIK, shadow-cljs assumes you won't run more than one instance of it per-project, so it only has info for one invocation stored under a project's .shadow-cljs directory.

**Additional context**

It seems like a better choice would be to have a dedicated subdirectory (e.g. .bb) and a directory per invocation pid (e.g. .bb/389 for pid 389), under which various state info could be recorded.  In this case, a file for a socket repl port could be recorded there (e.g. .bb/389/socket-repl.port).

The dedicated directory makes it clearer to the user and other tooling regarding the responsible entity.

This is more complicated though.

**Comment by sogaiu** [comment]
### Option 0

Do nothing.  Consider again if need arises.

### Option 1

Single file in project directory that records a port number.

Lein (.nrepl-port) and Boot (.nrepl-port, .socket-port) do this.

Concerns:

* file conflicts with other tooling
* "littering" project directories

### Option 2

Single file in a babashka-specific subdirectory (e.g. dir name: .babashka)

shadow-cljs does this (.shadow-cljs directory; nrepl.port, socket-repl.port, cli-repl.port files)

Concerns:

* appears to only support one process per project directory at a time

### Option 3

Per-process subdirectories of a babashka-specific subdirectory (e.g. .babashka/\<pid-1\>, .babashka/\<pid-2\>, etc.)  Each per-process subdirectory can contain a file per repl port (e.g. socket-repl-1.port, socket-repl-2.port)

Concerns:

* is the extra complexity really a worthwhile trade-off?

### Observations

Perhaps it is not clear at this point whether it's important to support multiple simultaneous processes associated with a single project directory.

May be there are other approaches that could be chosen that don't start out supporting multiple processes, but that could be easily extended to do so.

For example, it might seem a bit strange, but one could start with option 2 (.babashka directory plus files within), and later add additional sibling babashka-specific directories (e.g. .babashka-2 or .babashka-\<pid\>)

Another approach might be a hybrid where option 2 is chosen initially and then subsequent process invocations could use option3.  Writing code to support this on the tooling side might be more complex, but may be that's not such a big issue?

**Comment by borkdude** [comment]
For reference:

You can discover a random free port like this:

```
$ bb -e '(import java.net.ServerSocket) (with-open [sock (ServerSocket. 0)] (.getLocalPort sock))'
51611
```

and you can wait for a port like this:

```
$ bb -e '(wait/wait-for-port "localhost" 51611)
```

Maybe those ingredients are sufficient to get by without writing a file when editors start a babashka socket/nREPL server themselves.

**Comment by sogaiu** [comment]
Nice idea!

May be if deleteOnExit ends up working (don't remember if it does atm), that could be used too?

I still think the project root should be avoided as a location unless the name of the file indicates it's clearly a babashka-related file.

**Comment by martinklepsch** [comment]
`.deleteOnExit` works for me:
```diff
 (import [java.net ServerSocket]
+        [java.io File]
         [java.lang ProcessBuilder$Redirect])
 (require '[babashka.wait :as wait])
 (let [nrepl-port (with-open [sock (ServerSocket. 0)] (.getLocalPort sock))
       pb (doto (ProcessBuilder. ["bb" "--nrepl-server" (str nrepl-port)])
            (.redirectOutput ProcessBuilder$Redirect/INHERIT))
       proc (.start pb)]
   (wait/wait-for-port "localhost" nrepl-port)
   (spit ".nrepl-port" nrepl-port)
+  (.deleteOnExit (File. ".nrepl-port"))
   (.waitFor proc))
```

**Comment by borkdude** [comment]
Cool! In case `.deleteOnExit` did not work, one other way to do it is to install a shutdown hook using 

```
$ bb -e '(-> (Runtime/getRuntime) (.addShutdownHook (Thread. #(println "bye"))))
bye
```

**Comment by borkdude** [comment]
I'm closing this issue in favor of writing your own scripts. This offers the most flexibility to support the tooling the way you want it. I documented @martinklepsch's script in the nREPL [documentation](https://github.com/borkdude/babashka/blob/master/doc/repl.md#nrepl).
