### ISSUE TITLE
Should *in* behave as in Clojure by default?

### ISSUE THREAD

**Issue by j-cr** [borkdude/babashka#171]
**Is your feature request related to a problem? Please describe.**
It's confusing that `*in*` is bound to something completely different compared to vanilla clj; moreover, its behavior depends on a number of command line switches, and by default arguably the most surprising behavior is chosen.

TL;DR: I wanted to test this snippet but realized it doesn't work with babashka:

```
(with-open [rdr (clojure.java.io/reader *in*)]
  (println "started")
  (doseq [line (line-seq rdr)]
    (println line))
  (println "done")) 
```

**Describe the solution you'd like**
By default, `*in*` functions as in vanilla jvm clojure. Its behavior can be changed with command line switches. 

Alternatively, another special var can be introduced, so that `*in*` *always* behaves as in vanilla, and switches are applied to the new var, e.g. `*bb/in*`.

**Describe alternatives you've considered**
If backwards compatibility is desired, then instead a new switch (alternative to -i/-I) should be introduced that enables "vanilla `*in*`" mode.

**Additional context**
I hope that's not out of scope.

**Comment by borkdude** [comment]
The name `*in*` only has a special meaning in the default (`user`) namespaces. So either use an `(ns foo)` at the start of your script, or use `clojure.core/*in*` fully qualified.

**Comment by j-cr** [comment]
Ah! That's even more confusing if you ask me. :)

A possible counter-argument: a lot of one-liners in the examples use the `-i` switch anyway, so it won't make much difference typing-wise. On the other hand, benefits: compatibility/portability, least surprise, user-friendy.

In any case, thanks for explanation; probably deserves a mention in the readme and/or clarification in the help message. Feel free to close if you're rule it wont fix.

**Comment by borkdude** [comment]
@j-cr We could rename `user/*in*` to `user/*stdin*` to be be more portable with Clojure, but that would be a breaking change. I'll be needing the input from other babashka users to see what's their opinion.

So:

```
$ echo 'hello' | bb '*in*'
hello
```

Becomes:
```
$ echo 'hello' | bb '*stdin*'
hello
```

**Comment by borkdude** [comment]
https://github.com/borkdude/babashka/issues/173
