### ISSUE TITLE
Address possible name conflicts

### ISSUE THREAD

**Issue by j-cr** [borkdude/babashka#172]
**Is your feature request related to a problem? Please describe.**
The name `bb` unfortunately conflicts with already-existing linux packages, which might be a problem for packaging and wider adoption in the future.

- https://packages.debian.org/buster/bb
  Executable is named `bb`; the same package exists in other major distributions.

- https://www.debian.org/doc/debian-policy/ch-files.html
  > Two different packages must not install programs with different functionality but with the same filenames. <...> If this case happens, one of the programs must be renamed.

**Describe the solution you'd like**
1. Rename the executable. Pros: no conflicts. Cons: probably a longer name would be required. Breaking.
2. Leave it as is. Continue to rely on the install script and/or brew instead of traditional linux packaging ecosystem.

**Additional context**
I just thought the question should rather be raised while the project is still young. Also (not directly related to the issue) for me personally the name bb came into conflict with personal utils I already had; renamed it to `bsh`, which is, alas, [not any better](https://packages.debian.org/buster/bsh) in the context of this issue. Naming is hard!

**Comment by borkdude** [comment]
I guess if there will ever be an official debian package, it can be named bbk, bbka, babashka and people can make the bb alias themselves?

**Comment by j-cr** [comment]
`bbk` seems like a good fit, no conflicts and short, +1 to consider that as the default executable name for future releases.

**Comment by borkdude** [comment]
@j-cr I'm not going to change the name right now, but if there will be a debian package named like that, I might consider it. The reason is that the name might be taken between now and the creation of the debian package. I don't know when this will be released and who will create it.
