### ISSUE TITLE
str/join doesn't work?

### ISSUE THREAD

**Issue by PEZ** [borkdude/babashka#2]
This example from the README:

```sh
cat /tmp/test.txt | bb --raw '(shuffle *in*)' | bb --println '(str/join "\n" *in*)
```

Prints `nil` when I try it. MacOS Mojave. bb 0.0.3.

**Comment by borkdude** [comment]
@PEZ Hi Pez! I added this function after I released 0.0.3. You might want to look at cljdoc for version 0.0.3 for the examples that should work.
