### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by kannangce** [borkdude/babashka#20]
**version**

[ Please specify which version of babashka you're using. You can find this with `babashka --version`. The documentation on the master branch may be ahead of the most released version. You can check the docs for your version by going to cljdoc. ]

**platform**

[ Please specify which platform you are using babashka on, so you can test a
new binary when the issue is resolved. ]

**problem**

[ Please provide a short and to the point description of the problem ]

**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
@kannangce Can you give some more information of what you have tried to compile this project and what the unexpected behaviour was? See the template in your original post that you were supposed to fill out.

**Comment by borkdude** [comment]
Please try again with a reproduction of your problem.

**Comment by kannangce** [comment]
I tried running `script/compile` when I got the error. Then figured out `sci` is a submodule, hence I have to do a `git clone` with `--recursive` flag. It's working fine now. Mention about this in Readme would be helpful.

**Comment by borkdude** [comment]
@kannangce Thanks! Added it to the README now. Can you verify if this was a clear change to the README?

**Comment by kannangce** [comment]
Yeah. That'll be helpful for beginners.

**Comment by dpsutton** [comment]
I'm not seeing this in the readme. Have I missed it?

**Comment by borkdude** [comment]
@dpsutton https://github.com/borkdude/babashka/blob/master/doc/dev.md
