### ISSUE TITLE
Add features to support common fs operations

### ISSUE THREAD

**Issue by nate** [borkdude/babashka#200]
**Is your feature request related to a problem? Please describe.**

I'd like to build something similar to the [Clojure Commons fs package](https://github.com/clj-commons/fs) for file system manipulation in babashka.

**Describe the solution you'd like**

To figure out what I need I tried to get that package to work in babashka, although it doesn't seem like it's not going to work overall and I'm going to make something else.

Here's what I'd like to see added:

- [ ] java.io.FilenameFilter
- [x] java.nio.file.LinkOption
- [x] java.nio.file.CopyOption
- [x] java.nio.file.attribute.FileAttribute
- [x] java.lang.IllegalArgumentException (needs fully qualified name in babashka whereas in clj you can just use IllegalArgumentException)
- [ ] reify (for FilenameFilter)
- [x] clojure.java.shell/with-sh-dir
- [x] clojure.java.shell/with-sh-env

**Describe alternatives you've considered**

I've been shelling out for some things like when I need to glob when listing files and similar. I'd rather avoid shelling out.

**Comment by borkdude** [comment]
These classes are already in bb:

```
java.nio.file.CopyOption
java.nio.file.attribute.FileAttribute
```

**Comment by borkdude** [comment]
I've added everything with a mark in the original post. For now I'll not include `reify` + `FilenameFilter`. The latter is part of a very old API that's probably superseded by something in nio. E.g. take a look [here](https://stackoverflow.com/a/29316408/6264).
