### ISSUE TITLE
Difficulty with packaging babashka for linux distributions

### ISSUE THREAD

**Issue by crocket** [borkdude/babashka#206]
### Problem

* To make a package for Gentoo Linux, I need to let it manage dependencies. Babashka builds its own uberjar through leiningen. Leiningen fetches its own dependencies. How can I make leiningen pick dependencies from specific file paths given by an external source?
* GraalVM itself has to be packaged as a build dependency, but I don't know how to make this happen, yet.

### Solution

* Explain how to package babashka by building it from source.
* Provide an ant build file because gentoo linux supports ant for packages.
* Attach an uberjar to each release so that packagers can build binaries with an uberjar and GraalVM.
* ...

**Comment by borkdude** [comment]
There is a `script/build` which shows how to build this project, but it currently includes the uberjar step.

Providing an uberjar is something I do for other projects. If I would start doing that for this project, then you can skip the leiningen part. 

That seems to be the easiest option for both of us?

**Comment by borkdude** [comment]
Added the uberjar in the latest release:

https://github.com/borkdude/babashka/releases/tag/v0.0.57

**Comment by crocket** [comment]
Thanks.
