### ISSUE TITLE
Have a better error message for unrecognized cli option

### ISSUE THREAD

**Issue by jeroenvandijk** [borkdude/babashka#219]
**version**

Version: babashka v0.0.61-SNAPSHOT 

**platform**

Mac OSX

**problem**

```
bb -help
Could not resolve symbol: -help [at line 1, column 1]
```

**repro**

```bb -help```

**expected behavior**

Have a error message like `Didn't recognize options xyz` and maybe add `use --help for available options`

**Comment by borkdude** [comment]
When running bb with an argument that is not a CLI option, it is interpreted as a Clojure expression:

```
$ bb '(+ 1 2 3)'
6
```

I'm not sure if we should special case the warning for typos. What about:

```
$ bb '(+ 1 2 3 a)'
Could not resolve symbol: a [at line 1, column 10]
```
It would be weird if the error message now became: a is not a valid option.

**Comment by borkdude** [comment]
Maybe it makes sense to only interpret the argument as a Clojure expression when it starts with `(`,  `[`, or `{` ?

**Comment by jeroenvandijk** [comment]
Yeah I was about to type something like that. This is what I thought of:

As a potential alternative(s):
* when the expression starts with `-` assume it was intended to be a cli option
* when the expression fails look into potential other intensions

**Comment by borkdude** [comment]
But then it would try to open `-help` as a file, which would give you something like `Can't open file -help` warning.

**Comment by jeroenvandijk** [comment]
Another case of the same problem happening in the wild.

Executing a command in the wrong directory (path doesn't exist):
```
bb  src/adgoji/application/cli.cljc
[line 1, col 32] Invalid symbol: src/adgoji/application/cli.cljc.
```

Ideal feedback would be `file src/adgoji/application/cli.cljc does not exist`
