### ISSUE TITLE
Standalone Jar for v0.0.60 was named wrong it seems

### ISSUE THREAD

**Issue by didibus** [borkdude/babashka#224]
In the release Assets for v0.0.60 the standalone Jar is names:

```
babashka-0.0.60-linux-standalone.jar
```

I think this is the wrong name, it should be named:

```
babashka-0.0.60-standalone.jar
```

As based on the name of prior releases.

The wrong name could break some download scripts that expect it to be consistent.

Regards.

**Comment by borkdude** [comment]
Hi @didibus This renaming was done because the uberjar contains Unix-specific classes. May I ask what your use case is for the uberjar? I added it because someone might want to use it for a linux package, but I'm not sure if he is using it.

**Comment by didibus** [comment]
Nothing specific, I just noticed, and the compile shell script seems to be setup to pickup the old name, so I thought it was maybe a mistake. Didn't know that the uberjars were platform specific? How is that?

**Comment by borkdude** [comment]
@didibus There are a few of these classes:

https://github.com/borkdude/babashka/blob/c3830511944cf9bc83689ace2457bcc92ea438d4/src/babashka/impl/classes.clj#L166

to make interop with ProcessBuilder and java.nio.file.Path work. 

Using more type hints like in this commit:

https://github.com/borkdude/babashka/commit/f1b3180c760c4e3e3c6c6fe5ce983888a642e3a0

we should be able to get rid of them, but I don't want users to add more type hints than they are used to in Clojure. Some more improvements are needed for that. But once that's done, the uberjar might be renamed again without an OS-specific suffix, unfortunately breaking consumers of it, but afaik there are none or maybe one at the moment.

**Comment by didibus** [comment]
Cool I see. Ya it's all good then.
