### ISSUE TITLE
Consider writing hiccup lib or adding a hiccup namespace

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#229]
This could be implemented as a spartan.hiccup library first.
Should we expose hiccup.core directly or should we add a babashka.hiccup namespace?

**Comment by borkdude** [comment]
This hiccup function suffices for now: https://github.com/borkdude/babashka/blob/8c1077af00c818ade9e646dfe1297bbe24b17f4d/examples/notes.clj#L21

**Comment by plexus** [comment]
In case someone ends up here looking for a Babashka-compatible hiccup, here's a more feature-complete version: https://github.com/lambdaisland/open-source/blob/2cfde3dfb460e72f047bf94e6f5ec7f519c6d7a0/src/lioss/hiccup.clj

**Comment by borkdude** [comment]
@plexus Thanks Arne. Is this something we should list on the libraries page?

https://github.com/borkdude/babashka/blob/master/doc/libraries.md

**Comment by plexus** [comment]
Let me think about that. This is part of code that's definitely considered "internal" (i.e. specific to how lambda island libraries are managed) that I wasn't planning to release/announce as such, but it would make sense to release some of the more general purpose things.

**Comment by borkdude** [comment]
@plexus That's totally fine. The page also points to non-library scripts of other people in the "projects" part of that page.

**Comment by plexus** [comment]
ok, sure. Feel free to add it then. This one might be interesting for folks as well

https://github.com/lambdaisland/open-source/blob/master/src/lioss/subshell.clj

like `sh/sh`, but it inherits stdin/stdout/stderr, so that the user sees in real time what the subprocess is doing, and can possibly interact with it. More like how shelling out in a bash script works.

**Comment by borkdude** [comment]
@plexus I think there's a shortcut for this: https://github.com/lambdaisland/open-source/blob/master/src/lioss/subshell.clj#L8-L10

https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#inheritIO()
