### ISSUE TITLE
Install script fails on minimal ubuntu installation

### ISSUE THREAD

**Issue by spacegangster** [borkdude/babashka#233]
Hey,
Thanks for the awesome work!

Having a little corner case. Install script uses `unzip` which was not available on VPS provider edited OS distro of Ubuntu 18.04.

If you're alright with barbarious solutions – perhaps python3 could work (if it's available).

See a self-proving bash snippet below 
```
echo 'oh hi' > txt.txt
zip t.zip txt.txt
rm txt.txt
file=t.zip

python3 -c "
import sys
import sys
from zipfile import PyZipFile
print('will unzip $file')
pzf = PyZipFile('$file')
pzf.extractall()"

cat txt.txt
```

I'm alright with this being closed, sure it's much easier to just install unzip :)
Or perhaps you could consider a gzip package.
Looking forward to use it as a canary ansible replacement

Have a nice day ! :)

**Comment by borkdude** [comment]
If more people find .zip problematic over .tar.gz I'll also publish .tar.gz. For now I'm sure you can workaround this problem by making a script in your VPS named `unzip` which does the above thing with python3?

**Comment by spacegangster** [comment]
yeah, not a problem actually, I've just installed unzip, so no worries. I'm just contributing a corner-case :)

**Comment by borkdude** [comment]
Thanks. I'll let more people chime in on this issue. With enough votes, I'll make a .tar.gz. For now, I'll close it.
