### ISSUE TITLE
Publish to Docker Hub

### ISSUE THREAD

**Issue by hden** [borkdude/babashka#259]
**Is your feature request related to a problem? Please describe.**
When using babashka within a container (e.g. for CI), I find myself repeating the same installation script. Maybe we can publish an official image on the Docker Hub so that everyone can just build from there.

**Describe the solution you'd like**
Publish to the Docker Hub for every release.

**Describe alternatives you've considered**
It's fairly easy to setup my own repository, but an official status would encourage usage.

**Additional context**

```Dockerfile
FROM some/baseimage:latest

# Using the built artifact
COPY --from=borkdude/babashka:latest /usr/local/bin/bb /usr/local/bin/bb

ENTRYPOINT exec /usr/local/bin/bb
```

**Comment by borkdude** [comment]
@hden Sure, we can do that. I'm also doing that for clj-kondo:

https://github.com/borkdude/clj-kondo/blob/master/Dockerfile
https://hub.docker.com/r/borkdude/clj-kondo/

Changing that to babashka should be relatively easy.

**Comment by borkdude** [comment]
@hden I made a `Dockerfile`.  I'm trying to get it to run in Alpine, but so far this doesn't work yet:

```
bb: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

I'll have to figure out some details around this. Maybe you have an idea as well.

There is a (non working) image published to https://hub.docker.com/r/borkdude/babashka/.

**Comment by borkdude** [comment]
That now seems to work:

$ docker run borkdude/babashka:0.0.70-SNAPSHOT bb -e '(System/getProperty "java.vm.version")'
"GraalVM 19.3.1 CE"
