### ISSUE TITLE
Consider adding support for UNIX sockets

### ISSUE THREAD

**Issue by lispyclouds** [borkdude/babashka#275]
**Is your feature request related to a problem? Please describe.**
As mentioned in #220, if we want to support talking to Docker or something similar which uses HTTP over unix sockets, we need to add https://github.com/jnr/jnr-unixsocket to bb as Java has no native support for UNIX_DOMAIN sockets. This can be used to script docker actions specially if used via https://github.com/lispyclouds/clj-docker-client

**Describe the solution you'd like**
We need to add https://github.com/jnr/jnr-unixsocket or someting similar as a bundled class to achieve this. Then something like https://github.com/gnarroway/hato can be made to talk over unix sockets.

**Describe alternatives you've considered**
There are none as java doesn't support unix sockets out of the box.

**Comment by borkdude** [comment]
What would a script using curl + clojure.java.shell look like for this scenario? If we end up adding clj-http-lite (which doesn't support this) we could maybe cover the edge cases with curl?

**Comment by lispyclouds** [comment]
One way could be:
```clojure
(require '[clojure.java.shell :as sh])
(require '[cheshire.core :as jsonl])

(defn fetch-curl
  [{:keys [method path]}]
  (let [socket   "/var/run/docker.sock"
        url      (format "http://localhost%s" path)
        base-cmd ["curl" "--silent" "--no-buffer" "--unix-socket" socket url]
        cmd      (case method
                   :post (conj base-cmd "--request" "POST")
                   base-cmd)]
    (-> (apply sh/sh cmd)
        :out
        (json/parse-string true))))
```

**Comment by borkdude** [comment]
This seems good enough for me to cover this case. Would be nice to document!

**Comment by borkdude** [comment]
Added to the docs.
