### ISSUE TITLE
Can't destructure vector

### ISSUE THREAD

**Issue by Saikyun** [borkdude/babashka#29]
**version**
0.0.7

**platform**
MacOS

**problem**
When trying to destructure a vector, I get an error I don't understand.

**repro**
```
$ bb -i '(let [[keys & rest] [1 2 3]] keys)'
Could not resolve symbol: seq.
```

**expected behavior**
I'd get `1` back.

**Comment by borkdude** [comment]
@Saikyun Can you try with a newer version? Version 0.0.9 has been released.

**Comment by borkdude** [comment]
@Saikyun: 

```
$ /usr/local/bin/bb --version
babashka v0.0.9-2
$ /usr/local/bin/bb '(let [[keys & rest] [1 2 3]] keys)'
1
```

**Comment by Saikyun** [comment]
Yeah it works, thanks!
