### ISSUE TITLE
Add support for java.nio Watcher

### ISSUE THREAD

**Issue by agriffis** [borkdude/babashka#290]
**Is your feature request related to a problem? Please describe.**
I'd like to use WatchService which seems to come from java.nio.file.FileSystems (reading [baeldung](https://www.baeldung.com/java-nio2-watchservice))

**Describe the solution you'd like**
I think `java.nio.file.FileSystems` could be added to [classes.clj](https://github.com/borkdude/babashka/blob/master/src/babashka/impl/classes.clj) but I'm not sure if it was omitted intentionally.

**Describe alternatives you've considered**
I really haven't considered any alternatives yet. I'd like to use inotify-like watching from babashka, and it seems like this is probably the right approach.

**Additional context**
Happy to provide a PR, this is just my first foray into babashka so I'm pretty uncertain about everything.

**Comment by borkdude** [comment]
@agriffis Welcome to add the class + a test example that shows its usefulness in the context of bb (and to lock down that we need this class so if we accidentally remove it, a test breaks).
Also please take a note of the binary size before adding the class and after adding it and post it here. I'd like to keep track of the growing size of the binary, to have some idea about what caused it over time.

**Comment by agriffis** [comment]
Sounds good. Is there any information about building bb? I've scanned the README but I seem to be missing it.

**Comment by agriffis** [comment]
Oh, I just found doc/dev.md :+1:

**Comment by borkdude** [comment]
@agriffis I've added a branch now called `file-watcherr`. When compiling with this branch, the following now works:

```
(import 'java.nio.file.FileSystems)
(import 'java.nio.file.WatchService)
(import 'java.nio.file.Path)
(import 'java.nio.file.StandardWatchEventKinds)

(require '[clojure.java.io :as io])


(let [^WatchService watcher (.newWatchService (FileSystems/getDefault))]
  (.register ^Path (.toPath (io/file "/tmp")) watcher
             (into-array (type StandardWatchEventKinds/ENTRY_CREATE)
                         [StandardWatchEventKinds/ENTRY_MODIFY]))
  (loop []
    (let [key (.take watcher)]
      (println "changed!")
      (.pollEvents key)
      (.reset key)
      (recur))))
```

Change a file in `/tmp/` and it prints `"changed!".

**Comment by agriffis** [comment]
@borkdude Oh, fantastic, thanks! I had started to work on it but got distracted by world events. Looking forward to using this!

**Comment by borkdude** [comment]
@agriffis Can you try the built version of bb with this and see if this is sufficient for your use cases? I'm only adding this if some person is really going to use it, since it will grow the binary a bit.

In the #babashka_circleci_builds links to binaries built from CI are posted. Here is an excerpt:

borkdudeAPP [linux - file-watcher@880948eb548302d1f89ee631ac228e8f3bfee42c]: https://5001-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.76-SNAPSHOT-linux-amd64.zip





11:41 AM
[linux-static - file-watcher@880948eb548302d1f89ee631ac228e8f3bfee42c]: https://5003-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.76-SNAPSHOT-linux-static-amd64.zip
11:43 AM
[macos - file-watcher@880948eb548302d1f89ee631ac228e8f3bfee42c]: https://5002-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.76-SNAPSHOT-macos-amd64.zip

**Comment by agriffis** [comment]
@borkdude I'll certainly let you know. Might take me a few days though.

**Comment by sogaiu** [comment]
For comparison / reference, here are some links to Clojure file / directory watching things:

https://github.com/ibdknox/watchtower
https://github.com/gmethvin/directory-watcher
https://github.com/rplevy/ojo
https://github.com/juxt/dirwatch

At the time I looked into this before, I didn't end up with what I thought worked well on the typical 3 platforms.  However, time has passed and may be it's the case that for babashka some existing method is fine (I was looking before in the context of finding something that might work for use in a JVM program).

**Comment by borkdude** [comment]
@sogaiu confirmed that the above script worked for him on Windows

**Comment by borkdude** [comment]
One issue with the above approach is that there can be quite some delay (a few seconds). This can be helped with this approach https://stackoverflow.com/a/18362404/6264 and that depends on a private non-cross-platform class.

**Comment by sogaiu** [comment]
For the record, specifically what I did to build was:

* for GRAALVM_HOME use a path to graalvm-ce-java8-20.0.0
* copy the `src/babashka/impl/classes.clj` file from the `file-watcher` branch to the `windows-jvm20-jdk8` branch
* use the build script `script\compile.bat` that is on the `windows-jvm20-jdk8` branch

**Comment by borkdude** [comment]
An alternative to the Java interop approach may be using an external watch command like:

https://facebook.github.io/watchman/

So approaching it from the "how would I do it in bash" angle.

**Comment by sogaiu** [comment]
Another rust one appears to be:

https://github.com/grego/caretaker

Had success compiling both caretaker and eagle-eye on Windows, but had more luck getting caretaker to work, FWIW.

**Comment by agriffis** [comment]
@borkdude Sorry I haven't been able to work on this yet. Some quick thoughts though:

First, it's possible that I'm happy doing this in clojure instead of babashka, since I don't need fast startup time. I didn't realize that `#!/usr/bin/env clojure` is a thing... I'm still pretty new to the language and ecosystem.

Second, regarding external tools, I've previously written a couple versions of the tool I have in mind already using bash with entr or inotifywatch. The problem is that, on a large project, I want to debounce events so that the build waits for files to settle, and I also want to change the kind of build based on the files that changed. The external tools I've found don't seem up to this challenge—they all want to run something immediately based on the first file that generates an event.

**Comment by borkdude** [comment]
@agriffis I added `java.nio.file.FileSystems` now anyway, because it also helps with dealing with zip files. See #310.
