### ISSUE TITLE
[doc] document opening socket REPL from emacs + inf-clojure

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#295]
9:12 PM
Lukas Hi all, can anybody help me with connecting to a socket repl in emacs? I have cider installed and inf-clojure but both don't really work out of the box for me (I know I probably do something wrong :see_no_evil:)
Cider -> connect to a clojure repl doesn't seem to work and with inf-clojure i have no idea how to connect to the repl (babashka)
9:18 PM
borkdude @Lukas
What works for me:
$ bb --socket-repl 1666
M-x inf-clojure-connect <ret> localhost <ret> 1666 <ret>
This will open a socket REPL buffer. Then in your script file:
M-x inf-clojure-minor-mode
And then you can eval forms from your buffer. (edited) 
new messages
9:19 PM
Lukas :heart: thank you, and thanks for creating babashka :hugging_face:
9:20 PM
borkdude I'll try and document this at the bb repo.
9:20 PM
np, enjoy :wink:

**Comment by shivekkhurana** [comment]
[off-topic] Is there any technical limitation that stops us from using babashka with cider?

**Comment by borkdude** [comment]
@shivekkhurana Would be best to ask the CIDER maintainers (cc @bbatsov)

**Comment by bbatsov** [comment]
We need babashka to run nREPL. As long as there's some nREPL server to connect to, CIDER's in business. :-)

**Comment by borkdude** [comment]
@bbatsov What's the simplest possible reference implementation of a Clojure nREPL server we could copy into babashka?

**Comment by shivekkhurana** [comment]
@borkdude 
I just ran into shadow-cljs's implementation of nREPL. I don't know if it's the simplest possible ref. impl. but it might help.

https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/server/nrepl_impl.clj

**Comment by bbatsov** [comment]
@shivekkhurana That's not a server implementation - rather it's Shadow's version of piggieback (ClojureScript evaluation middleware).
