### ISSUE TITLE
Consider adding ns for env config loading

### ISSUE THREAD

**Issue by DarinDouglass** [borkdude/babashka#296]
**Is your feature request related to a problem? Please describe.**
Layering config from the environment on top of EDN is a pretty typical way to configure applications/scripts. There are libraries that do this in standard Clojure. However, given the size/scope of some of those libraries (and the fact that the one I tried to include couldn't be required), I feel it makes sense to have a simple ns in bb to handle this use-case.

**Describe the solution you'd like**
My ideal solution would be: a simple namespace with a single function that takes a map and overlays environment variables on top of it.

My ideal solution closely mirrors [cprop](https://github.com/tolitius/cprop) which I use extensively in my own work:

```clj
HELLO="world" => {:hello "world"}
DATABASE__PASSWORD="super-secrete"  => {:database {:password "super-secret"}}
SOME-KEY__INNER="1" => {:some-key {:inner 1}}

user=> (env/overlay {:database {:password "" :missing-from-env "1234"}})
{:database {:password "super-secret" :missing-from-env "1234"}}
```

**Describe alternatives you've considered**
None really, outside of maintaining my own overlay (which I currently do this in my bb library). However, it's small enough (and IMO useful enough) that it could probably go into bb proper.

**Additional context**
As mentioned, I have my own overlay code currently maintained in my personal bb library. If there's interest I can put up a PR.

**Comment by borkdude** [comment]
@DarinDouglass 

Can you send the link to your bb lib? Are you aware of `BABASHKA_CLASSPATH`, etc? 

See:
- https://github.com/borkdude/babashka/#babashkaclasspath
- https://github.com/borkdude/babashka/#classpath

**Comment by DarinDouglass** [comment]
Yep, I've tried to give `cprop` in the classpath but it fails at when it tries to require the namespaces. I've even tried adding the missing Java classes into bb proper. That route should work (I didn't get it to, but that's likely my error), but I figured the cost in bb size isn't worth the library, given how small [the actual implementation](https://github.com/DarinDouglass/babashka/blob/add-env-overlay/src/babashka_/impl/env.clj) turned out to be.

**Comment by borkdude** [comment]
@DarinDouglass What I meant is that your implementation (https://github.com/DarinDouglass/babashka/blob/add-env-overlay/src/babashka/impl/env.clj) can be loaded using BABASHKA_CLASSPATH. It doesn't nessarily have to be inside bb itself? Unless it becomes a very popular bb compatible library.

**Comment by DarinDouglass** [comment]
Ah gotcha. Yeah that's what I'm doing now with my local code.

Generally, this is a problem that I think is/will be a pretty common use-case (it was the first thing that I had to fix for my code to work). But time will tell.

I'm fine the code sits as a library.

**Comment by borkdude** [comment]
@DarinDouglass If you want to publish it as a bb compatible library in its own git repo, then we can list it here: https://github.com/borkdude/babashka/#tools-and-libraries

If more people are interesting in something like this, we can eventually consider adopting it. But for now I prefer the flexibility of libraries as this gives more room experimentation before committing to a solution.

**Comment by borkdude** [comment]
@DarinDouglass I added a branch called `cprop` which allows you to just load the entire `cprop` library:

```
$ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {cprop {:mvn/version "0.1.16"}}}')

$ rlwrap ./bb
user=> (require '[cprop.source :refer [from-env]])
user=> (:babashka-classpath (from-env))
"src:sci:..."
```

Let me know what you think. This adds about 295kb to the library but adding more general java classes to bb will allow it to support more libraries, so I think it might be worth it.

**Comment by DarinDouglass** [comment]
If you're fine with the size increase, this is a good solution to me! Thanks for the quick responses. I'm loving bb so far.

**Comment by borkdude** [comment]
Merged.
