### ISSUE TITLE
Add nREPL server

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#301]
I welcome anyone who is interested in the nREPL support for babashka to checkout the nrepl-server branch and test it with:

```
BABASHKA_DEV=true clj -A:main --nrepl-server 1667
```

and then connect to the server using their favorite clients. As of now CIDER doesn't work, but `lein repl :connect` does.

I accept PRs to the branch.

See https://github.com/borkdude/babashka/blob/master/doc/dev.md on how to start developing babashka.

TODO: 
- [x] add *e, *1, *2, *3
- [x] Handle exceptions
- [x] Implement `:load-file` op (when pressing C-c C-k in CIDER)
- [x] Add support for `println`
- [x] completions. 
- [x] unit tests using
- [ ] cider-interrupt

https://github.com/clojure/tools.nrepl/blob/c14eaa89dbb750e230530afd267cd53fdd486c51/src/main/clojure/clojure/tools/nrepl/middleware/interruptible_eval.clj

```
(def a (atom nil))
(future (reset! a (Thread/currentThread)) (loop [] (println "hello") (Thread/sleep 1000) (recur)))
(.stop @a)
(future (reset! a (Thread/currentThread)) (spit "/tmp/foo.txt" (range)))
(.stop @a)
```

This is probably going into another nREPL issue:

https://github.com/clojure/tools.nrepl/blob/master/doc/ops.md#interrupt
- [ ] cider-find-var

**Comment by borkdude** [comment]
@bbatsov Any pointers will be helpful.

**Comment by bbatsov** [comment]
Basically the key things are:

* Use bencode as the data format
* Implement some notion of (evaluation) sessions (even if it's fake and there are not isolated as in the reference implementation)
* Support the built-in nREPL ops (clone, describe, eval, interrupt, etc)

You don't really need to implement the server in terms of middleware (as the reference implementation), you just need a server that speaks the protocol (bencode + the built-in ops). I'm not aware of any tutorials (guess I'll have to write something at some point), but you can take a look at implementations like https://gitlab.com/technomancy/jeejah and https://gitlab.com/technomancy/ogion/, which are pretty simple.

**Comment by borkdude** [comment]
Work in progress in the `nrepl-server` branch.

<img width="396" alt="Screenshot 2020-03-22 23 47 57" src="https://user-images.githubusercontent.com/284934/77263394-7a3f0280-6c98-11ea-8ba9-afde957124ed.png">

**Comment by rymndhng** [comment]
I've been using the `nrepl-server` branch for some development so far using Emacs & CIDER. So far I've found CIDER + nrepl-server easier to use that than `inf-clojure`.

Here is my feedback so far:

Things that appear to work:
- cider-repl-set-ns
- cider-eval-defun-at-point :: This works okay, however it ignores the namespace the the file is within
- evaluation in the buffer

That that I would like to work:
- cider-load-buffer
- cider-load-file
- cider-interrupt
- cider-find-var

---

As a CIDER user, I see these messages when connecting:

```
WARNING: Can't determine nREPL's version.
Please, update nREPL to 0.6.0 (or newer).
         More information.WARNING: Can't determine Clojure's version. CIDER requires Clojure 1.8.0 (or newer).
         More information.WARNING: CIDER requires cider-nrepl to be fully functional. Some features will not be available without it!
         More information.
```

**Comment by bbatsov** [comment]
Regarding the messages - probably some changes will be needed on CIDER's end as well, as it makes some assumptions about the nREPL server it uses (there weren't any alternatives until recently). Probably we should add some notion of "language" metadata to the describe op, so that clients can know they are not talking to a Clojure server. 

For `find-var` to work out-of-the-box - CIDER evaluates some Clojure code to get this info and I'm not sure if the same code works with babashka. Alternatively if an `info` op is added to babashka's nREPL server CIDER will just use it. Normally, this comes from `cider-nrepl`, but the clients don't really care where the op is coming from - only the data returned is important.

**Comment by borkdude** [comment]
@rymndhng I took at a stab at cider-interrupt. On the JVM this relies on the `.stop` method of `Thread` and this is not available on GraalVM (see https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#threads). So for now I'll have to leave this feature out.
