### ISSUE TITLE
Consider add a simple template feature

### ISSUE THREAD

**Issue by robertluo** [borkdude/babashka#303]
It is quite common that using a template engine to manipulate strings or configuration files when do shell scripting.

[comb](https://github.com/weavejester/comb) is a small and simple library with minimum but useful function `eval` to handle most daily template jobs.

I already tested it and it is compatible with babashka.

**Comment by borkdude** [comment]
Nice find! I don't think it's necessary to add this as a built-in since you can already run this library as a babashka library right now:

```
 $ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {comb {:mvn/version "0.1.1"}}}')
$ rlwrap bb
Babashka v0.0.77-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[comb.template :as template])
nil
user=> (template/eval "<% (dotimes [x 3] %>foo<% ) %>")
"foofoofoo"
user=> (template/eval "Hello <%= name %>" {:name "Alice"})
"Hello Alice"
(def hello
  (template/fn [name] "Hello <%= name %>"))
#'user/hello
user=> (hello "Alice")
"Hello Alice"
user=>
```

**Comment by robertluo** [comment]
Yes it can work this way. 

I just wondering if it is a battery worth to include, and because it is really small (just a few lines of code) and it has a potential capability on working on yml, xml or other formats as a default solution to deal with them.

**Comment by borkdude** [comment]
@robertluo It seems your PR doesn't even compile. Which doesn't surprise me, because comb uses eval. And eval doesn't work in native-image.

**Comment by borkdude** [comment]
FWIW I have been considering templating before, by e.g. adding selmer: https://github.com/borkdude/babashka/issues/136

I want to wait a little longer to settle on more built-in things, since there are competing solutions. 
I get requests to add stuff every few days now. While most of this stuff could be useful, we'll have to maintain it basically forever once it's in.
