### ISSUE TITLE
[graalvm] Larger binary size on GraalVM 20, can't build with CircleCI 4gb 

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#309]
See https://github.com/oracle/graal/issues/2281

**Comment by borkdude** [comment]
See comment here: https://github.com/oracle/graal/issues/2136#issuecomment-619195166

**Comment by borkdude** [comment]
@sogaiu did some tests:

sogaiu some results using -Xmx4500m:
both xml and properties removed:
* 143 secs
* 3.91 gb max
* 55879720 bytes
* details: https://pastebin.com/r0UtACit
only properties removed:
* 165 secs
* 3.91 gb max
* 60921896 bytes
* details: https://pastebin.com/CuZBxWmZ

**Comment by sogaiu** [comment]
FWIW, those pastes will not remain valid for more than a month IIUC.

**Comment by borkdude** [comment]
@sogaiu That's ok, I think the summary has enough information to work with.
