### ISSUE TITLE
Add support for `use` to refer all Vars from a namespace

### ISSUE THREAD

**Issue by didibus** [borkdude/babashka#318]
**Is your feature request related to a problem? Please describe.**

When using the command line REPL, or simple REPLs like inf-clojure, a socket-repl, etc. I often make use of `use` to quickly load and refer to all Vars in a namespace. It is quite ergonomic for this use case.

I find it frustrating not to have it in babashka, especially since there isn't even support for using `:refer :all` inside `require`.

**Describe the solution you'd like**

I'd like it if babashka added support for Clojure's `use`.

**Describe alternatives you've considered**

I considered having support for `:refer :all` inside `require`, and I do not like it as much. There's a few reasons:

1. It isn't as quick to type.
2. I agree that in source code, I never want to see a `:refer :all` or the use of `use`, as they obscure the origin of Vars. And once you're in a file, it is easy to get some simple auto-complete on the namespace, or to explicitly `:refer [a b c ...]` each Var you intend to use, since you can at any point move back up and add extra Vars you forgot you were going to use to the `:refer`. BUT, if there were to be a possibility of it, I think having it be `use` is easier to spot and realize that a namespace is actually interning a bunch of unknown Vars form some other namespace, where as you need to pay extra attention to realize that `:refer` is used in combination with `:all`.

**Additional context**

At the REPL, I also don't use `use` inside the `ns` form. So I'm not asking for support of `:use` inside `ns`, but for support of the `use` function.

**Comment by borkdude** [comment]
Thanks. I added the clj-together label. If this project gets funded by Clojurists Together I can do it during the funding period.

**Comment by borkdude** [comment]
Implemented.
