### ISSUE TITLE
Improperly escaped character breaks REPL

### ISSUE THREAD

**Issue by Lokeh** [borkdude/babashka#337]
**version**

`Babashka v0.0.80 REPL.`

**platform**

macOS 10.14.6

**problem**

Typing an improperly escaped character in a string, such as `"\d"`, causes the REPL to break with strange errors.

**repro**

```
$ bb
Babashka v0.0.80 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> "\d"
clojure.lang.ExceptionInfo: [line 1, col 4] Unsupported escape character: \d.
```

This is expected, however, typing the following line shows the aberrant behavior:

```
user=> "\\d"
"\n"
user=> \\
user=> clojure.lang.ExceptionInfo: Could not resolve symbol: d [at line 2, column 4]
```

Continuing to try to use the REPL normally fails as well. Typing simply the string `"asdF"` outputs the following:

```
user=> "asdF"
"\n"
user=> clojure.lang.ExceptionInfo: Could not resolve symbol: asdF [at line 3, column 2]
```

Trying to evaluate an expression form hangs indefinitely:

```
user=> (+ 1 1)
```

**expected behavior**

Improperly escaped character should throw an error, but allow normal operation in the REPL thereafter.

**Comment by borkdude** [comment]
I believe this is no different than Clojure's REPL behavior of which the code is largely re-used:

```
$ clj
Clojure 1.10.2-alpha1
user=> "\d"
Syntax error reading source at (REPL:1:4).
Unsupported escape character: \d
"
"\n"
user=> (type *e)
clojure.lang.ExceptionInfo
```
