### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by maacl** [borkdude/babashka#339]
**version**
master

**platform**

Ubuntu 19.10
**problem**

Installer script fails with:
bash: /proc/self/fd/11: No such file or directory

**repro**

sudo bash <(curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install)

**expected behavior**

babashka installed

**Comment by borkdude** [comment]
@maacl Hi Martin. I could reproduce the same problem on one of my VPSes. It seems this works better:

```
$ curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-babashka
$ chmod +x install-babashka && ./install-babashka
```

**Comment by maacl** [comment]
Thanks, this works after adding sudo.

**Comment by borkdude** [comment]
@maacl The script also accepts an optional install dir argument if you don't want to use sudo.
