### ISSUE TITLE
Print link to nREPL documentation at server startup

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#344]
To document: 

- supported editors
  Environments that are known to work:
    - Emacs / CIDER
    - lein repl :connect
    - Calva
    - Chlorine
    - vim-iced
    - conjure
    - vim fireplace
- workaround tubular for Cursive: https://groups.google.com/forum/#!msg/cursive/GfbTm-Tut4M/r2VRlaCsBAAJ
- how to fabricate your own .nrepl-port file at startup: https://github.com/borkdude/babashka/issues/157#issuecomment-609754426
- For debugging you may use `BABASHKA_DEV=true bb --nrepl-server`

**Comment by martinklepsch** [comment]
Can confirm that the nREPL server works with Conjure:
```
babashka v0.0.82
conjure 656bf69e (develop)
```
