### ISSUE TITLE
Incorrect display of unicode characters

### ISSUE THREAD

**Issue by bfortz** [borkdude/babashka#359]
**version**
0.0.78

**platform**
Linux (nixos)

**problem**
UTF-8 encoded strings are not printed correctly.

**repro**
➜ ~ bb -e '(prn "bépo àê")'
"b??po ????"

**expected behavior**
"bépo àê"

**Comment by borkdude** [comment]
@bfortz I have tested this on macOS, with Docker and on Linux. They all seem to work correctly. Can you try again with that version? Could it be something in your environment?

```
$ bb -e '(prn "bépo àê")'
"bépo àê"

$ docker run --rm borkdude/babashka:0.0.85 bb -e '(prn "bépo àê")'
"bépo àê"
```

**Comment by bfortz** [comment]
Thanks for the quick answer. It seems to be a problem with the nixos packaging. Running in Docker or building bb directly in my working environment works perfectly. So I will try to fix the nixos package. Sorry for bothering you.
