### ISSUE TITLE
Experiment with JDBC / Postgres support

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#372]
See https://github.com/yogthos/graal-web-app-example/tree/postgres

- [x] postgres works (branch `jdbc`)
- [ ] mysql with `[mysql/mysql-connector-java "8.0.19"]` doesn't:
  - https://github.com/oracle/graal/search?q=mysql&type=Issues
  - https://gist.github.com/borkdude/6c6ff18cbc8c6436fde8066552d8edaf
  - https://github.com/oracle/graal/issues/418#issuecomment-391828456
  Maybe relevant?
  - https://github.com/mysql/mysql-connector-j/pull/41
- [ ] mysql with `[org.mariadb.jdbc/mariadb-java-client "2.6.0"]` doesn't:
    - https://gist.github.com/borkdude/4664cb57cd7d089cc442608282e884bd

Binaries:

- linux: https://7302-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.89-SNAPSHOT-linux-amd64.zip
- macOS: https://7300-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.89-SNAPSHOT-macos-amd64.zip

**Comment by seancorfield** [comment]
Thanks for trying MySQL. This Graal stuff certainly seems to be pretty "bleeding edge" :)

**Comment by borkdude** [comment]
@seancorfield In this case I don't think it's the bleeding edge-ness of GraalVM but more the difference between run-time initialisation and initialisation in a static initializer block.

E.g. when you compile this code to native:

```
(def x (System/getenv "FOO"))
```

`x` will be initialized at compile time, capturing the environment variable `FOO` from the compilation environment. In GraalVM-compatible code you should do something like this instead:

```
(defn -main []
  (let [foo (System/getenv "FOO"))] ...))
```

Apparently the mysql drivers initialise a `Thread` as part of a static initialiser block and GraalVM doesn't like this, because they can only deal with code that does not have such side effects. To be compatible that `Thread` should be started lazily / as part of the `-main`.

**Comment by borkdude** [comment]
Small mysql update:

When adding the dependency `[io.quarkus/quarkus-jdbc-mysql "1.4.0.Final"]` which contains substitutions to fix the above issue, I do have success compiling this with `[mysql/mysql-connector-java "8.0.19"]`. 

Program:

```
(require '[next.jdbc :as jdbc])

(defn mysql []
  (let [db {:dbtype   "mysql"
            :dbname   "godb"
            :host     "localhost"
            :port     3306
            :user     "gouser"
            :password "gopassword"}]
    (jdbc/execute!
     db
     ["create table if not exists foo ( name varchar(10) )"])))

(mysql)
```

However, when running it, I get an exception:

```
$ ./bb /tmp/jdbc.clj
clojure.lang.ExceptionInfo: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.WrongArgumentException [at /private/tmp/jdbc.clj, line 21, column 5]
```

Maybe some reflection configuration can fix this.

**Comment by borkdude** [comment]
One step closer:

```
$ ./bb /tmp/jdbc.clj
clojure.lang.ExceptionInfo: Cannot connect to MySQL server on localhost:3,306.

Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.

 [at /private/tmp/jdbc.clj, line 21, column 5]
```

and in the Docker container:
```
2020-04-23T19:20:13.866169Z 8 [Note] Aborted connection 8 to db: 'godb' user: 'gouser' host: '172.17.0.1' (Got an error reading communication packets)
```
So something is happening between bb and mysql now, but not yet correctly.

**Comment by borkdude** [comment]
I tried adding a bunch of classes that were referenced here to the reflection configuration: https://github.com/quarkusio/quarkus/blob/master/extensions/jdbc/jdbc-mysql/deployment/src/main/java/io/quarkus/jdbc/mysql/deployment/MySQLJDBCReflections.java, but could not get to a solution. This work has been pushed to the `jdbc-mysql` branch.

**Comment by borkdude** [comment]
We'll revisit mysql another time.
