### ISSUE TITLE
hsqldb support, some thoughts on the future of babashka, feature flags, splitting out in different command line utils?

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#382]
I've got hsqldb working too with babashka. 

For now, this feature is optional and can be enabled when you compile babashka yourself:

https://github.com/borkdude/babashka/blob/master/doc/build.md#optional-features

I discovered that Github issues can be sorted by emoticon. So if you would like hsqldb to be included by default, let me know by upvoting this issue with a thumbs up, even if the issue will be closed at some point.

## A few thoughts about the future of babashka:

- Adding support for hsqldb grows the binary with almost 10MB (from approx 50 to 60). Is this ok for most people? It is currently unknown how much other database drivers will add to bb. Going forward with more than only the postgres driver might be a road to bloating the bb binary. If this is a concern, or not at all, please post your opinion.
- Adding more libraries to babashka demands more from build environments like CircleCI and Github actions. The build now needs an -Xmx value of approx `4500m`. Eventually we will run out of memory again. We had this problem before with CircleCI and the memory got bumped from 4GB to 8GB. On Github actions we are contrained to 7GB of memory. On AppVeyor where we build the Windows version we are contrained to 6GB (although we could move that to CircleCI). In the future we'll have to either cut out libraries, or build on proprietary hardware, if the minimum needed -Xmx value exceeds a certain threshold.
 Maybe it makes sense to split out the sql stuff to a clj-jdbc command line that is a fork/branch of babashka that includes support for Postgres and HSQLDB? And another tool for xml and another for yaml?  

## HSQLDB

- linux binary: https://7486-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.90-SNAPSHOT-linux-amd64.zip
- macOS binary: https://7485-201467090-gh.circle-artifacts.com/0/release/babashka-0.0.90-SNAPSHOT-macos-amd64.zip

This article helped me getting hsqldb working: https://jluger.de/blog/20181219_native_java_microservice_graalvm.html

A test program:

``` clojure
(require '[next.jdbc :as jdbc])


(defn query []
  (let [db {:dbtype "hsqldb"
            :dbname "mem:testdb"}]
    (jdbc/execute!
     db
     ["create table foo ( x int )"])
    (jdbc/execute!
     db
     ["insert into foo values ( 6 )"])
    (jdbc/execute!
     db
     ["select * from foo"])))

(println (query))
```

**Comment by snorremd** [comment]
Note that I'm not a heavy user of babashka, but like the project very much.

I think keeping the binary small is good if you want babashka to be usable in memory constrained environments. Providing flavors of the binary for those that want extra builtin libraries makes sense to me. There is always that next very useful library people would want babashka to support out of the box, and I don't think the binary should grow forever.

With regards to the build issues of Circle CI resources. Will it be possible to build multiple binaries in the 250 provided free minutes?

**Comment by DarinDouglass** [comment]
We are currently using the Postgres support in babashka. It saves us from having to install, shell out to `psql`, and parse its output when we need to query a db.

This feels like a common-enough scripting situation, though I admit we may be holding the tool wrong.

I’m curious what the size difference would be between:

- bb with db support (and no db client)
- bb no db support + the necessary db client

**Comment by borkdude** [comment]
@DarinDouglass Adding support for postgres added about 3MB to babashka. But adding support for more databases, like in the case of hsqldb, adds around 10MB. Adding more and more drivers can quickly add up, maybe eventually doubling the size of babashka.

I'm going to experiment with another tool called `clj-jdbc` which is exactly like babashka, but with no YAML, no XML, etc. libraries, just support for JDBC + Postgres + hsqldb. 
Let's see if you can use that instead for the postgres part, would that be an option? Does it make sense to ONLY support JDBC + Postgres in babashka AND have another clj-jdbc tool that has more?

**Comment by borkdude** [comment]
Another comment by @DarinDouglass on Clojurians slack:

```
Yeah the CI resources could be an issue, if it IS an issue I’d likely pitch in some money to help make it NOT an issue.
As for the binary size, install size is far, FAR down my my personal list of concerns. I’d rather have a bigger core bb and have another minimal build for people whose use-case may also be more minimal than have support for tools (even ones that I don’t use like hsqldb) limited by “will this fit on super small machines?”.
What is 10MB to the hundreds of GB likely available to the majority of users?
```

**Comment by justone** [comment]
I agree on the binary size not being a problem. Downloading 100MB is no problem if it's a one time cost. My only thought on that is wondering when binary size starts to impact startup time. Machines are pretty fast these days, and usually once a program is run its contents are in memory for the next run, so it's not likely to be an issue.

At first, I thought this might be a `hugo`/`hugo-extended` situation where the `clj-jdbc` command line would be a superset of `bb`, and only *add* more things like JDBC support. In this situation, when your program needed JDBC support, you could just change the shebang line and everything would work. The downside of this is that it wouldn't help with build times, it would only shift them to the `clj-jdbc` project.

Now that I understand the idea is to make a separate CLI that is like a minimal bb + JDBC support that you would shell out to, it raises the question of IPC. If you shell out to `clj-jdbc`, how do we get data back from that application quickly and efficiently. For small data sets, EDN or transit are fine, but maybe something like nippy would work well too?

**Comment by borkdude** [comment]
@justone Piping EDN via stdin/stdout to and from bb would be an option.

**Comment by borkdude** [comment]
Here is a hypothetical version of `clj-jdbc` which supports Postgres, HSQLDB and possibly more in the future: https://github.com/borkdude/clj-jdbc/blob/master/README.md

**Comment by borkdude** [comment]
I have some more data on memory usage.

Hsqldb:
```
[bb:27909]    classlist:   5,443.64 ms,  1.70 GB
[bb:27909]        (cap):   1,974.46 ms,  2.32 GB
[bb:27909]        setup:   3,806.46 ms,  2.32 GB
[bb:27909]     (clinit):     861.83 ms,  4.55 GB
[bb:27909]   (typeflow):  18,860.35 ms,  4.55 GB
[bb:27909]    (objects):  23,669.69 ms,  4.55 GB
[bb:27909]   (features):   1,422.43 ms,  4.55 GB
[bb:27909]     analysis:  46,590.59 ms,  4.55 GB
[bb:27909]     universe:   1,262.41 ms,  4.57 GB
[bb:27909]      (parse):   4,100.86 ms,  4.61 GB
[bb:27909]     (inline):   2,933.22 ms,  4.59 GB
[bb:27909]    (compile):  22,088.09 ms,  4.75 GB
[bb:27909]      compile:  31,923.52 ms,  4.75 GB
[bb:27909]        image:   5,316.08 ms,  4.59 GB
[bb:27909]        write:   1,369.93 ms,  4.67 GB
[bb:27909]      [total]:  96,207.29 ms,  4.67 GB
```

Master:
```
[bb:28143]    classlist:   4,608.00 ms,  1.67 GB
[bb:28143]        (cap):   1,309.69 ms,  2.27 GB
[bb:28143]        setup:   2,485.56 ms,  2.27 GB
[bb:28143]     (clinit):     714.89 ms,  4.36 GB
[bb:28143]   (typeflow):  19,880.71 ms,  4.36 GB
[bb:28143]    (objects):  17,814.99 ms,  4.36 GB
[bb:28143]   (features):   1,373.66 ms,  4.36 GB
[bb:28143]     analysis:  41,565.32 ms,  4.36 GB
[bb:28143]     universe:   1,256.95 ms,  4.69 GB
[bb:28143]      (parse):   2,684.25 ms,  4.44 GB
[bb:28143]     (inline):   4,027.67 ms,  4.62 GB
[bb:28143]    (compile):  20,630.73 ms,  4.70 GB
[bb:28143]      compile:  29,844.40 ms,  4.69 GB
[bb:28143]        image:   4,698.83 ms,  4.63 GB
[bb:28143]        write:   1,203.46 ms,  4.63 GB
[bb:28143]      [total]:  86,070.25 ms,  4.63 GB
```

So the `hsqldb` branch peaked at `4.75 GB` and master is peaking at `4.70 GB`. So the analysis of hsqldb by GraalVM only costs 50m memory more than compared to master. It still adds 10MB to the binary size. 

So the extra memory pressure doesn't seem to be much of a problem specifically for hsqldb 

Is adding support for hsqldb to babashka worth the extra 10MB binary size?
Compressed the binary becomes around 20 MB, unzipped 60-70 MB.

It is currently unknown how much other database drivers will add to babashka.

**Comment by borkdude** [comment]
This would be the kind of thing that's possible with an embedded hsqldb in bb:

https://github.com/borkdude/babashka/blob/hsqldb/doc/examples.md#find-unused-vars
https://github.com/borkdude/babashka/blob/hsqldb/examples/hsqldb_unused_vars.clj

I ported that example from another script in the examples directory where I used sqlite by shelling out.

**Comment by didibus** [comment]
What about `bb` being the full shebang with everything under the sun (as long as startup times are still fast). And maybe looking into a build script where someone could choose to build a custom `bb` with certain modules removed?

So people who are constrained on bundle size have a nice path forward?

**Comment by highleverage** [comment]
My thoughts: it would be great to have all nice stuff (db, curl etc) under the current name but also distribute stripped versions for someone who really cares about the binary size. Something like “brew install bb —no-curl —no-hsqldb“. I know it doesn’t solve ci issue, but from ergonomic perspective it’s more intuitive

**Comment by lukaszkorecki** [comment]
As a preface: people like me will push for making bb a replacement of regular Clojure where resource usage (RAM and startup time) is a concern. For my team, bb quickly went from "oh this is cool" to "we have a tool based on bb monitoring our production system". 
From there I started thinking about other use cases where we can use bb and with recent Postgres driver addition it started to look like it could be viable option in more scenarios than I originally anticipated.

With that in mind, I think it's fair to push compilation burden on people like me: if I have an option to run a build command and add the modules I need, that's absolutely fine. Running out of CI resources is something I haven't considered.
This reminds me of how tools like `weechat` work: if you want Guile scripting - you have to build it yourself and instruct the build process to include the language support. By default you only get Python. In the similar vein: if someone needs H2 or RabbitMQ support, they could somehow hook into babashka build setup and produce a binary with the required bits.

Alternative would be to do something akin to Terraform's plugin system: https://www.terraform.io/docs/plugins/basics.html - the core binary defines an RPC interface, and all other functionality is provided as separate binaries and capabilities are discovered and used via common interface. So placing bb.jdbc binary somewhere would make it available to the core bb interpreter (how?) and keep the core lean.

Not sure if it's a good idea, just putting it out there as TF had to solve extensibility problem, but also provide a cross-platform way of doing that.


Lastly, binary size is not a concern for me - for comparison: Terraform binary + AWS provider is over 200MB already. if you add more providers it becomes quite silly.

I hope these comments help in any way!

**Comment by borkdude** [comment]
@lukaszkorecki I like the idea of making some features option that users can compile themselves if not everybody needs them or if they aren't that common for scripting.

I merged HyperSQL support to master. This can be compiled with `BABASHKA_FEATURE_HSQLDB` set to `true`:

https://github.com/borkdude/babashka/blob/master/doc/build.md#optional-features

If this feature turns out to be super useful for enough people, I will consider making it part of the standard distribution.

**Comment by borkdude** [comment]
I discovered that Github issues can be sorted by emoticon. So if you would like hsqldb to be included by default, let me know by upvoting this issue with a thumbs up.

**Comment by borkdude** [comment]
Some JDBC dev notes here: https://github.com/borkdude/babashka/blob/master/doc/dev.md#jdbc

**Comment by borkdude** [comment]
In v0.0.90 HSQLDB is available under a feature flag. See https://github.com/borkdude/babashka/releases/tag/v0.0.90.
