### ISSUE TITLE
write postgres test using embedded postgres

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#388]
https://github.com/opentable/otj-pg-embedded

**Comment by kolharsam** [comment]
@borkdude I'd like to help with this if that's alright.

**Comment by borkdude** [comment]
@kolharsam Sure!

Right now, JDBC + Postgres support is behind a feature flag. But I think it would be nice if we could test the JDBC / Postgres functionality when running the tests in on the JVM using an embedded Postgres. Same for HSQLDB. 

So:

- add the embedded postgres driver to the test dependencies in project.clj
- same for the hsqldb driver
- implement unit tests for postgres + hsqldb (in memory) in namespace: babashka.jdbc-test
- only run it when `babashka.test-utils/jvm?` is true, so we don't have to build a native image for it (those features are not part of the standard build)

Also see:

- the test suite of https://github.com/seancorfield/next-jdbc. 
- script/postgresql-test: this test runs using a Docker container, but that doesn't work in CI

**Comment by kolharsam** [comment]
@borkdude,
question regarding the unit tests that have to be written...

would they have to be as extensive as they are in `next-jdbc` or just the `basic` & `connectivity` test suites are good enough? 

I've never written tests like these and so I'd like to know what kind of tests we write for databases?

Also, will the tests be run behind the feature flags?

**Comment by borkdude** [comment]
@kolharsam The test is basically already there:

https://github.com/borkdude/babashka/blob/master/test-resources/babashka/postgresql_test.clj

It's basically just a sanity check to see if this functionality still works. Take a look around in the other tests for examples.

The only difference to be able to run this with embedded postgres is the driver name: `:dbtype "embedded-postgres"` instead of `:dbtype "postgres"` (although it could be  worth trying if it just works with `postgres`). 

Here is some test code from next.jdbc that uses this embedded driver:

https://github.com/seancorfield/next-jdbc/blob/780c75954176ade9d523eb3f1bda001b5bdc0b95/test/next/jdbc/test_fixtures.clj#L98

**Comment by kolharsam** [comment]
@borkdude you can track the work on https://github.com/borkdude/babashka/pull/409

Also, when I ran `lein deps` I'm not able to install all dependencies. I get an error that I could not retrieve certain resources like `edamame`. How do I rectify this?

And about `:dbtype` where is that key available?

Apologies, that I keep asking about elementary issues.

**Comment by borkdude** [comment]
@kolharsam You can read how to clone the repository with submodules here: https://github.com/borkdude/babashka/blob/master/doc/dev.md

`:dbtype` is an argument in the map to be passed to `next.jdbc. See the example: https://github.com/borkdude/babashka/blob/master/test-resources/babashka/postgresql_test.clj.

**Comment by kolharsam** [comment]
@borkdude have updated the PR mentioned on here: https://github.com/borkdude/babashka/issues/388#issuecomment-622670732

I've marked it as a work in progress since I am not completely convinced about what I've done and needed your inputs to proceed further.

**Comment by borkdude** [comment]
@kolharsam The code looks good, but you'll have to start the embedded postgres server outside babashka in a JVM (as it's not part of babashka itself) and then run the queries inside babashka. This test just runs all of the code in one and the same JVM. Take a look at some of the other tests in `test/bababashka` to see how this is done. A good example would be `babashka.udp-test` which starts a UDP server in the JVM and then expressions inside babashka are executed to talk to that UDP server. We need something similar for this Postgres test.

**Comment by kolharsam** [comment]
Have made the necessary changes.

**Comment by borkdude** [comment]
@kolharsam Apart from putting code in another namespace, what does this accomplish?

**Comment by kolharsam** [comment]
Sorry @borkdude, I don't think I understood the phrase `start the server on the JVM` correctly then. The `udp-test` reference that you gave just run tests similar to what is being done in the file here. So if you could clear this part it would be helpful

**Comment by borkdude** [comment]
@kolharsam Your tests aren't running anything through babashka. You are simply testing if an embedded postgres driver works with a Clojure program in the JVM.

Take another look at the UDP tests. This code is evaluated by babashka:

```
(tu/bb nil
             "-e" "(load-file (io/file \"test-resources\" \"babashka\" \"statsd.clj\"))"
             "-e" "(require '[statsd-client :as c])"
             "-e" "(c/increment :foo)")
```

Splitting up into two different namespaces is not the point.

**Comment by kolharsam** [comment]
@borkdude have made some changes. Is it better now?

**Comment by borkdude** [comment]
@kolharsam Can you explain to me what you changed and why it would fix https://github.com/borkdude/babashka/issues/388#issuecomment-628736880?

**Comment by kolharsam** [comment]
@borkdude 

All tests are running now. Which wasn't happening earlier as you noted.

**Comment by borkdude** [comment]
The point I was trying to make in https://github.com/borkdude/babashka/issues/388#issuecomment-628736880 was the the code you are testing is not code executed by babashka, but just in a JVM. That's why I referred to the UDP tests as an example of how something is started in a JVM and then connected to from code that's run inside babashka.

**Comment by kolharsam** [comment]
So essentially the queries are executed using babashka?

**Comment by borkdude** [comment]
@kolharsam Exactly.

**Comment by kolharsam** [comment]
@borkdude I keep running into this error 

```
"clojure.lang.ExceptionInfo: Unable to resolve classname: com.opentable.db.postgres.embedded.EmbeddedPostgres [at /xxx/babashka/test-resources/babashka/embedded_pg_server.clj, line , column ]\n"}
```
I did make sure that `BABASHKA_CLASSPATH` has this dependency prior to executing the test

**Comment by borkdude** [comment]
@kolharsam 

The server should be started in the JVM, not in babashka.  The server needs to know about the class `com.opentable.db.postgres.embedded.EmbeddedPostgres`, but babashka doesn't need to know what driver the server is using. That class is not part of the code that babashka is running.

Then you should connect from babashka to this running server using a db spec and execute the queries.

**Comment by kolharsam** [comment]
My latest commit, I think is a step in the right direction. 🤞
Queries are now being executed on `tu/bb`.
All tests are now running.

**Comment by borkdude** [comment]
@kolharsam How can I run this test? E.g. the UDP test I can run with:

```
$ lein test :only babashka.udp-test
==== Testing JVM version

lein test babashka.udp-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```

Can you give me a similar command line to run your test?

**Comment by kolharsam** [comment]
@borkdude have updated the tests. The tests can be run with `script/postgresql_test`
Tests are now evaluated on both `bb` and the JVM

**Comment by borkdude** [comment]
@kolharsam The tests are still failing on CI:

![Screenshot 2020-05-17 23 22 37](https://user-images.githubusercontent.com/284934/82160402-63cab700-9895-11ea-946b-3441c268c256.png)

It seems your test always runs regardless of the `BABASHKA_FEATURE_POSTGRESQL` environment variable, which needs fixing.

**Comment by borkdude** [comment]
When I run the script locally I see this, which also seems to be the problem on CI:

```
$ script/postgresql_test
==== Testing JVM version

lein test babashka.postgresql-test
=== test-ns-hook

"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
"Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
```

**Comment by kolharsam** [comment]
@borkdude I belive it's the port number that is causing the trouble here. You had it as `54322` and I forgot to change it back to that. I've fixed that, so hopefully that should be alright now.

**Comment by kolharsam** [comment]
@borkdude I think the tests are passing...now.

**Comment by borkdude** [comment]
@kolharsam Made some comments in the PR.
