### ISSUE TITLE
Can't use `bb -i '*in*' in eshell

### ISSUE THREAD

**Issue by Saikyun** [borkdude/babashka#39]
**version**
0.0.13

**platform**
MacOS + Emacs 26.1

**problem**
This works:
```
$ bb -i '(+ 1 2 3)'
6
```

This hangs until I interrupt:
```
$ ls | bb -i '*in*'
interrupt: 2
```

It works in my MacOS terminal, but I basically only use emacs, so it'd be neat if it worked in eshell, and I think it did before I updated `bb`.

**repro**
Call `$ ls | bb -i '*in*'` in `eshell`.

**expected behavior**
Not hanging.

**Comment by borkdude** [comment]
Can you verify if this used to work with 0.0.12? Do you have a theory why it might work differently in eshell?

**Comment by Saikyun** [comment]
It was 0.0.7 that I used. How would I test that? I mean, how would I install the old version? :)

Hm, well, maybe `bb -i '*in*'` waits for a specific character or something, that eshel doesn't send? I know there are various quirks with eshell, but generally stuff just works. So I sadly don't know much about the specifics.

**Comment by borkdude** [comment]
You can download previous versions from Github and put them on your path. Check with —version if you are using the right version.

**Comment by borkdude** [comment]
This is the link to 0.0.7 for MacOS: https://github.com/borkdude/babashka/releases/download/v0.0.7/babashka-0.0.7-macos-amd64.zip

**Comment by borkdude** [comment]
@Saikyun I see no difference with version 0.0.7 in eshell, it also seems to hand in eshell.

**Comment by borkdude** [comment]
Since I don't know how eshell works, I'm closing this for now, until someone comes with a suggestion how to fix it.

**Comment by borkdude** [comment]
@Saikyun One debugging example:

```
 echo "1\n" | clojure -e '(str "x" (read-line) "x")'
```

This works in bash, but not in eshell. No clue why.

**Comment by Saikyun** [comment]
It's strange, I get the same behaviour in `shell-mode` as well (which runs bash). I know `clj` doesn't work, because the terminal width is set to `0`, but other than that, I don't know much about the specifics of emacs shell-modes... If I find anything out I'll share the information.

**Comment by Saikyun** [comment]
Since it works in `shell-mode` I'll just resort to that for now. :) If I figure anything out wrt eshell I'll tell you.
