### ISSUE TITLE
Add support for clojure.pprint/*print-right-margin*

### ISSUE THREAD

**Issue by cldwalker** [borkdude/babashka#405]
Hi again. Thanks again for your wonderful tool. I have a clojure.pprint feature request. I'm more than happy to submit a PR for it. Before I do, I wanted to run it by you

**Is your feature request related to a problem? Please describe.**
I'd like for `clojure.pprint/*print-right-margin* ` to just work. I've confirmed locally that this is equivalent to fipp's :width. I also see cider [sees the two as equivalent](https://github.com/clojure-emacs/cider-nrepl/pull/414/files#diff-f67f9f971853925d3646b0272f6e449c)

**Describe the solution you'd like**
I'd like to conditionally add it to theseo options:
https://github.com/borkdude/babashka/blob/137d39821f8686764b656a56bff3f3620a121985/src/babashka/impl/clojure/pprint.clj#L11

**Describe alternatives you've considered**
It's either supported or not

**Additional context**
n/a

Cheers

**Comment by cldwalker** [comment]
Related to this request, when I try to use `with-bindings` I get `clojure.lang.ExceptionInfo: Could not resolve symbol: with-bindings`. Is this something that can easily be added? I see some references to with-bindings in here as well as sci

**Comment by borkdude** [comment]
Added both the dynamic var and `with-bindings`.

**Comment by cldwalker** [comment]
Thanks! You're awesome! 🕺 💃
