### ISSUE TITLE
babashka pods

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#411]
The native library experiment turns out harder than we thought. It might be simpler to have "pods" (yes, let's just use that word, since the word library is already quite overloaded) that can communicate via stdin and stoud using EDN or JSON. These pods can in theory be implemented in any language: Clojure, Go, Rust, whatever, as long as they fulfil the protocol.

You could do `(babashka.pods/load-pod "bb-pod-hsqldb")`. 

The plugin has an nREPL-esque way of communicating via bencode as the base message format. At minimum it supports the following ops:

- `describe` - example return value: 

```
{"format" "edn"
 "vars" [{"namespace" "pod.hsqldb"
           "name" "execute!"}]}
```

- `invoke` with `"var"` and `"args"` (args encoded in EDN, or JSON, according to `"format"` in `"describe"`) - example return value: `{"value" "1"}`

`bb` will do some registration, spin up the binary, insert a shutdown-hook, etc. 
You can then do `(require '[hsqldb.jdbc])`. bb will know this namespace is associated with the module). It will just proxy anything under the `hsqldb.jdbc` namespace to the binary and the binary can respond with "unknown thing" if it doesn't know the operation, resulting in an exception.

See `examples/pods`.

**Comment by sogaiu** [comment]
I get a 404 for the link: https://github.com/borkdude/babashka/blob/pods/libhsqldb/test.clj

**Comment by borkdude** [comment]
@sogaiu That link is no longer up to date. Check the repo for `examples/pods`.
