### ISSUE TITLE
Support java.util.Arrays/copyOf

### ISSUE THREAD

**Issue by cldwalker** [borkdude/babashka#415]
Hi. Throwing up a not important request for supporting a Java library. If if it's something I can do given some direction, I can give it a try.

**Is your feature request related to a problem? Please describe.**
I was looking to use https://github.com/aysylu/loom in a script. When I `(require 'loom.alg-generic)`, I get an error `clojure.lang.ExceptionInfo: Could not resolve symbol: java.util.Arrays/copyOf [at loom/alg_generic.cljc, line 482, column 12]`

**Describe the solution you'd like**
It would be nice to require loom and have it work as it does in Clojure

**Describe alternatives you've considered**
I could try to submit a PR to loom to change it to use another java class. Unlikely they would take a PR to have it work for babashka

Cheers

**Comment by borkdude** [comment]
@cldwalker I added the method to master. I tried this library as well, but it uses defrecord which is not (yet) compatible with bb. Working on it.

**Comment by cldwalker** [comment]
Thanks for adding anyway ❤️
