### ISSUE TITLE
Make pods available on the JVM

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#420]
We can do this by publishing `babashka.impl.pods` as a separate library `babashka.pods` that takes some configuration of how to create a namespace and insert vars with the proxy functions into the namespaces.

**Comment by kolharsam** [comment]
Is it possible to _save_ these configs? I only thought about that because they could essentially serve as blueprints for all pods that you might create. Would this be a valid use case of these changes were to be made? 

I'd like to help with this if that's ok.

**Comment by borkdude** [comment]
@kolharsam Thanks for your offer. If I need help, I'll let you know. I just created this issue so I could mention the issue number in the commit, but not something I would need help with.
