### ISSUE TITLE
Streaming Shell Command Output ala conch

### ISSUE THREAD

**Issue by vxe** [borkdude/babashka#422]
**Is your feature request related to a problem? Please describe.**

For long running shell commands, eg a big wget can upon completion (potentially after a long time), which is kind of ugly and doesn't have that shell command feeling when running (no progress feedback)

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/4325947/81479774-4e40f780-91da-11ea-86f0-a1c9fbda6cc4.png">

**Describe the solution you'd like**

Essentially conch streams the output to stdout instead of collecting it into the shell output map

https://github.com/Raynes/conch#low-level

**Describe alternatives you've considered**

It looks like echo -ne is a bash way to re-draw a progress bar looking thing

https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script

**Additional context**

**Comment by borkdude** [comment]
@vxe This is what `ProcessBuilder` is for: 

https://github.com/borkdude/babashka/issues/299
