### ISSUE TITLE
Add java classes to support tools.namespace

### ISSUE THREAD

**Issue by cldwalker** [borkdude/babashka#424]
Heyo. It would be great to add a few java classes to enable support for tools.namespace. I could try adding it to impl/classes.clj if you'd like. I would need some pointers on when to put something in one var vs another e.g. custom-map vs classes 

**Is your feature request related to a problem? Please describe.**
I'm attempting to run https://github.com/cognitect-labs/test-runner on a babashka project e.g. `bbk -A:test:runner` using your bbk alias. I get back an error `clojure.lang.ExceptionInfo: Unable to resolve classname: java.io.InputStreamReader [at clojure/tools/namespace/find.clj, line , column ]
`. It seems that adding a couple java classes would enable tools.namespace and test-runner to run

**Describe the solution you'd like**
Add the following missing java classes for [tools.namespace](https://github.com/clojure/tools.namespace/blob/master/src/main/clojure/clojure/tools/namespace/find.clj):
- java.io.InputStreamReader
- java.util.jar.JarFile
- java.util.jar.JarEntry

**Describe alternatives you've considered**
I believe this is a blocker to using the test-runner with babashka

Cheers

**Comment by borkdude** [comment]
@cldwalker After adding these classes, I run into:

> clojure.lang.ExceptionInfo: Could not resolve symbol: defprotocol [at clojure/tools/namespace/dependency.clj, line 14, column 2]

Alas. I did add these classes so we're prepared when the support for `defprotocol` ends up in sci.

**Comment by cldwalker** [comment]
Thanks! My bad on missing this was protocol dependent
