### ISSUE TITLE
Add test for shell macro

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#429]
https://gist.github.com/borkdude/63a86a04f5d97aae4825326c0309dad2#file-macro-clj-L18

**Comment by jeff303** [comment]
@borkdude , I want to work on this, but unclear on where to make the change.  This gist is referring to a `clj` file (obviously containing macros) not in in this repo.  Should it be added here, then a test written?  Or are you just looking for a new gist that has has this one with a test added?

**Comment by borkdude** [comment]
This issue is slightly outdated. There is now https://github.com/babashka/babashka.process which has a similar macro. 

Are you looking for stuff to do in general or specifically this issue?

**Comment by jeff303** [comment]
> This issue is slightly outdated. There is now https://github.com/babashka/babashka.process which has a similar macro.
> 
> Are you looking for stuff to do in general or specifically this issue?

Looking to get my feet wet with another Clojure project besides Specter.  Several people suggested this one, and it also seems like something I will personally use as I get more familiar with it.  Happy to help in any way that is most urgent (I'm reasonably self sufficient once pointed to the right place).

**Comment by borkdude** [comment]
@jeff303 Good to know. If you feel like it, there's an open issue at babashka.curl that might be fun to work on? 

https://github.com/borkdude/babashka.curl/issues/26
