### ISSUE TITLE
Potentially infinite stream of output after disconnecting from socket repl

### ISSUE THREAD

**Issue by sogaiu** [borkdude/babashka#44]
**version**

0.0.15-SNAPSHOT (790f0d4dba85c81ad9bccd00bd0481cdcf73fbbd)
 
**platform**

Manjaro Linux

**problem**

After connecting to the socket repl, evaluate something such as a number (e.g. 1), then disconnect via ^D.  The result here is a potentially infinite stream of bb=> nil on my screen.  

**repro**

See **problem** :)

**expected behavior**

No such potentially infinite stream.

**Comment by borkdude** [comment]
Can you check with commit `851fb4b5459459fef5c5dfb9816976a5ec0884ea`?

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/babashka/commit/4a485d51a00e82149e5b5ae7521fabd2c2aeb108

**Comment by sogaiu** [comment]
Thanks!
