### ISSUE TITLE
Get rid of storeXML and loadXML methods of java.Properties in reflection config

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#445]
The reason for this is that when upgrading to 20.1.0 it will include XML-related things that we don't need, that results into 6MB more binary size.

We generate `reflection.json` using the script `script/reflection`.
The actual config happens in `babashka.impl.classes`.
Documentation: https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md

To confirm it worked, one needs to compile with both 19.3.2 and 20.1.0 java8 and the resulting binary size should be more or less the same. This can be tested locally by downloading both GraalVM distributions and switching between them using the `GRAALVM_HOME` environment variable.

**Comment by borkdude** [comment]
@kolharsam Is this something you might be interested in doing?

**Comment by kolharsam** [comment]
@borkdude yup, sure!

**Comment by borkdude** [comment]
@kolharsam I already tried this locally. No need to work on this issue anymore.

The outcome is that ignoring `storeXML` and `loadXML` from `java.util.Properties` saves 1 mb, not the 6mb I was hoping for.
