### ISSUE TITLE
NullPointerException silences error location

### ISSUE THREAD

**Issue by cldwalker** [borkdude/babashka#446]
Heyo. Found a behavior that was inconsistent with how other errors are reported so I thought it'd be helpful to report

**version**
0.0.96

**platform**
osx
**problem**
If any bb code I run has a NullPointerException, the reported error doesn't contain the error's location, unlike other errors that are thrown

**repro**

In npe.clj:
```clj
(defn wow [str]
  (str/includes? str "FOO"))

(wow nil)
```

Then run it and observe:
```
$ bb -f npe.clj
java.lang.NullPointerException
```

**expected behavior**
Expected error to print:
```
java.lang.NullPointerException [at /path/to/npe.clj, line 2, column X]
```

**Comment by kolharsam** [comment]
@cldwalker I noticed this too. But looking at the trace after executing

```clojure
(defn wow [str]
    (str/includes? str \"FOO\"))
(try (wow nil)
    (catch Exception e (prn e)))
```

It looks like it has something to do with sci and maybe this method: https://github.com/borkdude/sci/blob/b94e53b7023b247025cf2d3e452219b817f35e1d/src/sci/impl/interpreter.cljc#L421 (I might be totally wrong about it) what do you think?

**Comment by cldwalker** [comment]
Works on 0.0.98. Thanks!
