### ISSUE TITLE
Unexpected behavior with wrong -main definition

### ISSUE THREAD

**Issue by martinklepsch** [borkdude/babashka#454]
**version** 0.0.99

**platform** Mac

**problem**

A wrong `-main` definition (`def` instead of `defn`) causes the script to run as you would expect but then NPEs just before exiting.

**repro**
```clj
;; cat src/mkl/error.clj
(ns mkl.error)

(def -main []
  (println "abc"))
```

```
$ bb -cp src -m mkl.error
abc
java.lang.NullPointerException: [at line 1, column 34]
```

**expected behavior**

Fail completely I guess?

**Comment by borkdude** [comment]
We should fail with `Too many arguments to def`.
