### ISSUE TITLE
Feedback on ergonomics of babashka

### ISSUE THREAD

**Issue by lucywang000** [borkdude/babashka#457]
I'm working on a new project and, as usual, need to write some helper scripts. Before I'd just use python or shell, but this time i want to try babashka. After spending 1 (very enjoyable, thanks for creating babashka!) hour or so I finally got my script done. Here are some (IMHO) things that could greatly improve the efficiency but at the moment is missing when compared to scripting in python.

1. Some common utils like os.path in python like `path.join`, `path.abspath`, `path.exists`
```python
os.path.join("/tmp", "scratch", "foo)
#  "/tmp/scratch/foo
```
2. An out of the box `glob` implementation. For bash there is wildchards, for python there is glob.glob.

Yes, all these could all be implemented, but most of the scripts I write would always make use of them here and there. So I think they deserve some out of the box support, like how bb.curl etc.

**Comment by borkdude** [comment]
Hi @lucywang000, thanks for your feedback!

About 1:

In Clojure this can be achieved as follows:

path.join: `(.getPath (io/file "foo" "bar"))`
path.abspath: `(.getAbsolutePath (io/file "foo"))`
path.exists `(.exists (io/file "foo"))`

About 2:

When I need to select files, I usually write `(filter (fn [f] (foo? (.getPath f))) files)` where `foo?` is a predicate on a `java.io.File`. To get a list of all files from a directory you can use `file-seq`.

This might not be as ergonomic as Python (depends on what you're used to), but in my experience sufficient and importantly, compatible with what Clojure users  already know 

Having said that, there are some interesting experiments around writing Clojure libraries which wrap `java.nio`:

https://github.com/nate/fs

I think it's better to let these libraries evolve in user space. Eventually when one of those stands out, it can become something like `babashka.fs`.

**Comment by borkdude** [comment]
Maybe it's good to just include clj-commons/fs though. People who want to improve that library can make PRs over there and eventually it will be updated in babashka. I'm going to gather some user feedback before taking that decisision.

**Comment by borkdude** [comment]
This isn't quite what you asked for, but Java has a class which supports glob patterns:

https://docs.oracle.com/javase/7/docs/api/java/nio/file/PathMatcher.html

This file wasn't part of babashka yet, but I'll add it for the next release, so people can write something like:

https://github.com/borkdude/babashka/commit/0389ed71274bfbc0aa3a7fc6dceed53b578e8f6d#diff-afe5b02b2f9c65cdf4862811d0f68479

**Comment by lucywang000** [comment]
@borkdude  Thanks for the links! I think https://github.com/clj-commons/fs is pretty useful.

Yeah I implemented all those before I posted this issue. My point is, if bb aims to be a powerful tool for scripting (it's almost there!), it'll benefit greatly from a more ergonomic "stdlib" out of the box. 

1. for "thinner" tasks, there is already cool things like java.io, data.csv, bb.curl etc. I just miss those goodies like `glob`, `os.path`, `subprocess`, `tempfiles` etc ... that's available out of the box from python stdlib - it's true that I could implement all of them on top of existing build blocks (e.g. os.path is no more than a group of string/file helper functions), but when all the small pieces adds up it could make the difference of "writing a script in 3min" and "writing a script in 30min".

2. For those "heavier" tasks, we already have pod as the way to go. One thing I feel missing is to have a "catalog" of bb pods, so people could install it easily. E.g. if I want to use bootleg I'll have to "google it => open its home page => open its release page => download => unzip => mv ". OTOH if there is builtin support for discovery and downloading, e.g.
```sh
bb --install-pod bootleg=1.0.0 sqlite=3.31
```
So this one-liner could replace all the 5 or 6 steps we need to get a pod right now, and it would make things so much easier!

If you think that's a good idea, to achieve that I think there are three parts:
1. where to host these pods?  github
2. where to keep the catalog? we actually may not need a catalog, just `bb --install-pod <user>-<project>-<pkg>=<version>` and try to locate it from github releases
3. the naming convention? this is necessary for locating the pod asset download link

**Comment by borkdude** [comment]
@lucywang000 

Thanks a lot for the feedback, I much appreciate this. 

Something I want to prevent is re-inventing a package manager for babashka. For libraries on the classpath `$BABASHKA_CLASSPATH` we already piggyback on existing tools such as `clojure` or its babashka port https://github.com/borkdude/deps.clj. This does the heavy lifting of resolving transitive dependencies and downloading them and producing a classpath. I can imagine there could be a similar solution for pods, e.g. using `brew`. Since pods are a very new thing, I would like to give this some time for good patterns to emergy, before implementing it.
I think lot can already be done with some amount of user provided scripting. E.g. @plexus has made this installer script for babashka which is run before a user of that repo invokes a script, to check if bb has already been installed. Adding pods to such a script would be fairly trivial:
https://github.com/lambdaisland/open-source/blob/master/bin/bb

About the fs library: I've personally never needed one so far, although I can image that if you compare `clojure.java.io` to Python, it's not nearly as ergonomic. 

In this phase of babashka I want to provide the raw building blocks. Eventually we can make babashka more ergonomic based on those building blocks and good practices. 

Thanks again for your feedback. There is also a babashka channel on Clojurians slack where you can post your feedback and questions.

**Comment by lucywang000** [comment]
@borkdude Thanks for sharing the insights. Sounds great to me!

**Comment by borkdude** [comment]
A user shared this link: https://hyperpolyglot.org/scripting2
Might be nice to add a bb column.

**Comment by didibus** [comment]
Want to point out, bb also supports libraries. All the utils you mention which you could write in 30min and make yourself a small bb lib which you use add-classpath to pull into your script. No pods necessary.

**Comment by davidpham87** [comment]
You could also add your functions in preloads or on your classpathes.

**Comment by plexus** [comment]
@lucywang000 here's a `bb` compatible `glob` implementation https://github.com/lambdaisland/open-source/blob/master/src/lioss/shellutil.clj#L46-L65

**Comment by borkdude** [comment]
Babashka 0.1.0 was just released and this contains the `PatchMatcher` class which allows one to leverage glob functionality from the JVM itself:

https://github.com/borkdude/babashka/blob/8c949dbe81d7a8f3ab1278cf6e6a400055e74dc7/test-resources/babashka/glob.clj#L4

**Comment by borkdude** [comment]
@plexus Are all your scripts here runnable with babashka? https://github.com/lambdaisland/open-source/tree/master/src/lioss? Can I list them under babashka projects here? https://github.com/borkdude/babashka/blob/master/doc/libraries.md#projects

**Comment by plexus** [comment]
Most of them are, all except `releases.clj` I think. Feel free to link to them, but as I mentioned somewhere else this is internal tooling for how we manage lambda island projects. Several things in there could be spun off into libraries but we're not doing that at this point, so we're also not promoting this stuff or taking PRs for them.

**Comment by borkdude** [comment]
@plexus Yeah, the projects section just serve as examples and are not intended as libraries, so that's ok. I'll add a link.

**Comment by borkdude** [comment]
Link added: https://github.com/borkdude/babashka/blob/master/doc/libraries.md#lambdaislandopen-source

**Comment by borkdude** [comment]
Work in progress at https://github.com/babashka/nio

**Comment by borkdude** [comment]
@lucywang000 We now have a catalogue pods: https://github.com/babashka/pod-registry

**Comment by borkdude** [comment]
@lucywang000 We also have babashka.fs now in babashka. 

https://github.com/babashka/fs
