### ISSUE TITLE
Support for clojure.datafy

### ISSUE THREAD

**Issue by cldwalker** [borkdude/babashka#468]
Hi. Exciting that [defprotocol support](https://github.com/borkdude/sci/issues/279) is out! I'm opening this issue to track support for clojure.datafy.

~~Soon after defprotocol support landed on master, I tried requiring `clojure.datafy` and ran into missing java classes e.g. ` Unable to resolve classname: java.lang.Iterable [at clojure/core/protocols.clj, line 34, column 6]`. Here's what I tried to remedy missing java classes:~~

EDIT:
I'm able to require clojure.datafy with [this branch](https://github.com/cldwalker/babashka/tree/datafy-2). This branch adds all the java classes that namespace required. However when I try to exercise datafy functionality via clojure.datafy/datafy or clojure.datafy/nav, I don't see the expected behavior. To reproduce what I'm seeing, run the built ./bb of the above branch against [this file](https://gist.github.com/cldwalker/4bf72c5c120f05f117508b9556969e04) e.g. `bb -f explore_data_nav.clj`. Observe that `nav-to-link` starting with [this invocation](https://gist.github.com/cldwalker/4bf72c5c120f05f117508b9556969e04#file-explore_datafy_nav-clj-L119) returns a number instead of an expected map.

It's unclear to me if I'm adding java classes in the wrong places, if there's a sci issue with defprotocol or something else. The above failing example only navigates maps. Any thoughts?

**Is your feature request related to a problem? Please describe.**
Would like to use clojure.datafy for navigating clojure data and java classes because of its first class reach in the language

**Describe the solution you'd like**
Would like require clojure.datafy to work

**Describe alternatives you've considered**
There isn't another that has the same functionality and is built into the language

**Additional context**
n/a

**Comment by borkdude** [comment]
@cldwalker `:extend-via-metadata` isn't supported yet in `defprotocol`. I'll make a new sci issue for that.

**Comment by borkdude** [comment]
Added `:extend-via-metadata to bb master now.

**Comment by borkdude** [comment]
@cldwalker I think clojure.datafy has to be added as a built-in namespace (either in sci or bb) due to some differences of what can be datafied (e.g. a sci namespace vs a clojure.lang.Namespace). 

What would be some useful example of having this in bb?

**Comment by djblue** [comment]
Hi @borkdude, I might have a use case. I was thinking of adding support for the babashka runtime to [portal](https://github.com/djblue/portal). So far I have a basic [http-socket-server](https://github.com/djblue/portal/commit/94e8924eda5669d3409a7c3db2ef4f2a1474d138) server setup, but things started to fail when I pulled in clojure.datafy. Let me know if there is anything I can do to help.

**Comment by borkdude** [comment]
@djblue I think this has to be built into the Clojure interpreter itself:

https://github.com/borkdude/sci/issues/355

It's on my list of things to look at, but feel free to experiment with it.

**Comment by cldwalker** [comment]
@borkdude Sorry for the delay. My use case is that have a knowledge graph that I'm able to navigate with REBL. I'd like to build a bb CLI that recreates and improves on navigating basic data structures like maps, sets and vectors. Another use case I could see for datafy is being a a helpful documentation reference for any java class or clj data structure e.g.:

```
$ echo "(require '[clojure.datafy :as d]) (->> Iterable d/datafy :members vals (map first) clojure.pprint/print-table)" |clj                                                                               
Clojure 1.10.2-alpha1
user=> nil

|       :name |          :return-type |   :declaring-class |              :parameter-types | :exception-types |               :flags |
|-------------+-----------------------+--------------------+-------------------------------+------------------+----------------------|
|     forEach |                  void | java.lang.Iterable | [java.util.function.Consumer] |               [] |           #{:public} |
|    iterator |    java.util.Iterator | java.lang.Iterable |                            [] |               [] | #{:public :abstract} |
| spliterator | java.util.Spliterator | java.lang.Iterable |                            [] |               [] |           #{:public} |
nil
user=>
```

I updated the first comment with a branch that is able to require clojure.datafy but I'm unable to observe working functionality.  I don't know when I'll dig into this more but thought it'd be helpful to share progress

**Comment by borkdude** [comment]
I added a branch `datafy` where I mounted the `clojure.datafy` namespace.

So this works:

```
$ ./bb "(require '[clojure.datafy :as d]) (d/datafy (atom 1))"
[1]
```

But somehow memory usage during compilation spikes and the binary gets quite bloated (95MB). I would like to see more details about why this happens, before continuing.

**Comment by borkdude** [comment]
This is pretty weird. Just including a reference to `(p/datafy ..)` results into this bloat.

This is the patched namespace I was using:
https://github.com/borkdude/babashka/blob/694fb1b4273780e31412d699c3c920d22d2fb6f0/src/babashka/impl/clojure/datafy.clj

**Comment by borkdude** [comment]
This could be explained by some other dep loading `clojure.datafy`:

```
user=> (binding [clojure.core/*loading-verbosely* true] (require '[clojure.datafy]))
nil
user=> (keys (:impls clojure.core.protocols/Datafiable))
(nil java.lang.Object java.lang.Throwable clojure.lang.IRef clojure.lang.Namespace java.lang.Class)
```

**Comment by borkdude** [comment]
Discovered that the dep loading `clojure.datafy` was `clojure.reflect` which was loaded by core.async.

Commit 82016da407671fff7bfbe4360a037d179286846d in branch datafy:

```
$ export BABASHKA_FEATURE_CORE_ASYNC=false
$ script/uberjar && script/compile
```

This yields a normal sized binary. More research needed. Maybe we can patch `clojure.reflect` and/or `clojure.datafy` itself on our classpath, so no matter who loads it, they will have our version.

**Comment by borkdude** [comment]
Turns out that `clojure.reflect` isn't the problem, it's the `Datafiable` for `clojure.lang.Namespace` that gets a bloated binary.

**Comment by borkdude** [comment]
```
$ ./bb --verbose "(require '[clojure.datafy :as d]) (d/datafy Exception)"
{:bases #{java.lang.Throwable}, :flags #{:public}, :members {java.lang.Exception [#clojure.reflect.Constructor{:name java.lang.Exception, :declaring-class java.lang.Exception, :parameter-types [java.lang.String java.lang.Throwable], :exception-types [], :flags #{:public}} #clojure.reflect.Constructor{:name java.lang.Exception, :declaring-class java.lang.Exception, :parameter-types [java.lang.String], :exception-types [], :flags #{:public}} #clojure.reflect.Constructor{:name java.lang.Exception, :declaring-class java.lang.Exception, :parameter-types [java.lang.Throwable], :exception-types [], :flags #{:public}} #clojure.reflect.Constructor{:name java.lang.Exception, :declaring-class java.lang.Exception, :parameter-types [], :exception-types [], :flags #{:public}}]}, :name java.lang.Exception}
```

**Comment by borkdude** [comment]
@cldwalker Your example seems to work (minus the fact that `Iterable` isn't yet available in `bb`):

```
$ ./bb "(require '[clojure.datafy :as d]) (->> String d/datafy :members vals (map first) clojure.pprint/print-table)"

|                  :name |                :type | :declaring-class |                      :flags |
|------------------------+----------------------+------------------+-----------------------------|
| CASE_INSENSITIVE_ORDER | java.util.Comparator | java.lang.String |   #{:public :static :final} |
|                 charAt |                      | java.lang.String |                  #{:public} |
|                  chars |                      | java.lang.String |                  #{:public} |
|            codePointAt |                      | java.lang.String |                  #{:public} |
...
```

**Comment by borkdude** [comment]
Part 1 is merged: support for `clojure.datafy` namespace. Implementing the `clojure.core.protocols/Datafiable` protocol within bb scripts will be part 2.

**Comment by borkdude** [comment]
In the `datafiable` branch:

```
$ ./bb "(require '[clojure.core.protocols :as p] '[clojure.datafy :as d]) (extend-type Number p/Datafiable (datafy [n] {:number n})) (prn (p/datafy 1)) (prn (keys (d/datafy *ns*)))"
{:number 1}
(:name :publics :imports :interns)
```

**Comment by cldwalker** [comment]
@borkdude This is all exciting work! Thanks for getting part 1 in. [This example](https://gist.github.com/cldwalker/4bf72c5c120f05f117508b9556969e04) seems to works for me now

**Comment by cldwalker** [comment]
I confirmed with the datafiable branch I'm able to navigate my data structures as in clj! I wasn't able to in master due to failing to require `clojure.core.protocols`

**Comment by borkdude** [comment]
Pushed final commits to the datafiable branch.

**Comment by djblue** [comment]
@borkdude Looks good to me. I was able to nav the hacker news api in babashka 🎉

**Comment by cldwalker** [comment]
Latest datafiable branch works great with my knowledge graph! 🕺

**Comment by borkdude** [comment]
Merged!
