### ISSUE TITLE
Can't require library namespace in Windows

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#469]
@4mitch There are a couple of issues that I've found while trying to make it work.

For starters, for some reason I can't capture the output of `clojure` into an environment variable, but it did work with [`deps.exe`](https://github.com/borkdude/deps.clj):

```
 $env:BABASHKA_CLASSPATH=(deps.exe -Spath -Sdeps '{:deps {org.clojure/data.zip {:mvn/version \"1.0.0\"}}}') | Out-String  
```

Now the classpath is set correctly which can be verified with:

```
PS C:\Users\borkdude\Downloads> .\bb
Babashka v0.1.1-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (System/getenv "BABASHKA_CLASSPATH")
"src;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\clojure\\1.10.1\\clojure-1.10.1.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\data.zip\\1.0.0\\data.zip-1.0.0.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\spec.alpha\\0.2.176\\spec.alpha-0.2.176.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\core.specs.alpha\\0.2.44\\core.specs.alpha-0.2.44.jar\r\n"
```

But for some reason I still can't require `clojure.data.zip.xml`. 

Maybe it has to do with the double slashes. I'll have to dig deeper.

**Comment by 4mitch** [comment]
Thank you a lot for your efforts! 
I didn't give up as well :) 
Also found a way to get classpath with deps.
But I still do not understand how **bb** is able to require some lib from JAR classpath 🤔
It won't work for me like this

> $ bb -cp "src;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/data.zip/1.0.0/**data.zip-1.0.0.jar**;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar"
> Babashka v0.1.1 REPL.
> Use :repl/quit or :repl/exit to quit the REPL.
> Clojure rocks, Bash reaches.
> 
> user=> (require '[clojure.data.zip.xml :as xml])
> java.lang.Exception: Could not require clojure.data.zip.xml. [at line 1, column 1]
> 

but like THIS is OK! It works with .clj sources!

> $ bb -cp "src;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar;C:/Users/dmitrii.fomin/.gitlibs/libs/data.zip/data.zip/ad
> **fb093974b967e380b1b50454bc9a78760a36ed/src/main/clojure**;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar;C:/User
> s/dmitrii.fomin/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar"                                                            
> Babashka v0.1.1 REPL.                                                                                                                                      
> Use :repl/quit or :repl/exit to quit the REPL.                                                                                                             
> Clojure rocks, Bash reaches.                                                                                                                               
>                                                                                                                                                            
> user=> (require '[clojure.data.zip.xml :as x])                                                                                                             
> nil                                                                                                                                                        
> user=> (doc x/xml->)                                                                                                                                       
> -------------------------                                                                                                                                  
> clojure.data.zip.xml/xml->                                                                                                                                 
> ([loc & preds])                                                                                                                                            
>   The loc is passed to the first predicate.  If the predicate returns                                                                                      
>   a collection, each value of the collection is passed to the next

**Comment by 4mitch** [comment]
And it seems that **bb** on Windows does not eat backslashes 🤔
So I prepare _-cp_ string like this 
`deps -Sdeps "{:deps {data.zip {:git/url \"https://github.com/clojure/data.zip\" :sha \"adfb093974b967e380b1b50454bc9a78760a36ed\"}}}" -Spath | bb -i -e "(with-out-str (print (str/replace (first *input*) (char 92) (char 47) ) ))"`

But I wonder why _this piping_ to bb do not work. BB just jumping out :(

> $ deps -Sdeps "{:deps {data.zip {:git/url \"https://github.com/clojure/data.zip\" :sha \"adfb093974b967e380b1b50454bc9a78760a36ed\"}}}" -Spath | bb -i -e "(with-out-str (print (str/replace (first *input*) (char 92) (char 47) ) ))" | bb -cp
> Babashka v0.1.1 REPL.
> Use :repl/quit or :repl/exit to quit the REPL.
> Clojure rocks, Bash reaches.
> 
> user=> "src;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar;C:/Users/dmitrii.fomin/.gitlibs/libs/data.zip/data.zip/adfb093974b967e380b1b50454bc9a78760a36ed/src/main/clojure;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar;C:/Users/dmitrii.fomin/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar"
> user=>
> Dmitrii.Fomin@RUWS04344-01 C:\dev\clojure
> $
>

**Comment by borkdude** [comment]
I found the issue, it has to do with searching in a jar file with `foo\bar` instead of `foo/bar`: I accidentally picked the platform specific file separator there.

**Comment by borkdude** [comment]
Confirmed that it works now:

```
PS X:\> $env:BABASHKA_CLASSPATH=(deps.exe -Spath -Sdeps '{:deps {org.clojure/data.zip {:mvn/version \"1.0.0\"}}}')
PS X:\> lein bb -e "(require '[clojure.data.zip.xml])"
```

Fixed with https://github.com/borkdude/babashka/commit/6ce94bdd86626cd5d3673a48c6fe0a565ca0f9a2

This new binary should work: https://ci.appveyor.com/api/buildjobs/xanef0w3etcs3p2e/artifacts/babashka-0.1.2-SNAPSHOT-windows-amd64.zip

**Comment by 4mitch** [comment]
Thank you very much!

**Comment by 4mitch** [comment]
Interesting,
seems bb is not quite suitable for walking over huge xml files for the moment
I test with 8Mb xml file - first time is for (-> fname java.io.FileReader. xml/parse)  , second - for (last items) and third for (count items).
Deps is in one order faster than bb 🤔
 
> **deps** .\bb-xml-test.clj
> "Elapsed time: 172.0963 msecs"
> value of last:  0.0
> "Elapsed time: **2780.141** msecs"
> total count 2484
> "Elapsed time: 27.16 msecs"

vs

> **bb** .\bb-xml-test.clj
> "Elapsed time: 2.3832 msecs"
> value of last:  0.0
> "Elapsed time: **28147.0738** msecs"
> total count 2484
> "Elapsed time: 7.1769 msecs"

**Comment by 4mitch** [comment]
Is there any chance to realize `clojure.xml` with babashka?
I found that **deps** can `(-> fname clojure.xml/parse)` and then handle it for 200Mb xml file  for about

> "Elapsed time: 12961.4986 msecs"
> total count 31409
> "Elapsed time: 5664.5169 msecs"
> 

But the same with `(-> fname java.io.FileReader.  clojure.data.xml/parse)` and then handle it - goes out with `OutOfMemoryError` (I have 8Gb) after a minute of struggling with much more memory spent than first approach 🤔

**Comment by borkdude** [comment]
@4mitch Could you post the XML and test code somewhere, so I can have a look?

bb is interpreted while clojure on the JVM is compiled. for some use cases where there are many nestings and loops, interpretation may add too much overhead and then using the JVM might be better.

**Comment by 4mitch** [comment]
@borkdude I'll try to find another suitable open sourced XML and make an example. My one has commercial information.
