### ISSUE TITLE
Add clojure.pprint

### ISSUE THREAD

**Issue by Saikyun** [borkdude/babashka#47]
**Is your feature request related to a problem? Please describe.**
When printing data it could be nice to have access to `clojure.pprint` and more specifically `clojure.pprint/pprint`. :)

**Describe the solution you'd like**
Adding a alias, e.g. `clojure.pprint` as `pp`.

**Describe alternatives you've considered**
Since this is most useful when "debugging"/playing around, the other thing I was thinking about is if one could run e.g. `ls | bb -r` to start a repl process where `*in*` is set to what `ls` pipes to `bb`. But I figure that might be overkill. This request makes the assumption that adding `clojure.pprint` is simple, and won't interfere with other plans. If that assumption is false, this request can safely be ignored.

**Comment by borkdude** [comment]
I'm in favor of this idea, but I might go for fipp or some other pretty printer, since that works well with GraalVM. I haven't been able to use clojure.pprint (unchanged) with GraalVM.

**Comment by Saikyun** [comment]
Ah, all right. I came up with some more context:
One issue I have atm is that if I have a collection of lines (e.g. `(= *in* '("a", "b", "c"))`, I can't really come up with a good way to print them nicely. If I just return them it can get unwieldy, and I can't use `doseq` nor `doall`, so I don't know how to run `println` multiple times either.

**Comment by Saikyun** [comment]
Here's an example: `ls -la | bb -i '(map #(apply str (drop 10 %)) *in*)'`
If we imagine that `ls -la` is log information or similar, where each line is too wide for the screen, I'd want to cut off the first 10 letters, then print all the lines as `ls -la` would. :)

**Comment by Saikyun** [comment]
It'd also be pretty cool if a pretty printer (whichever you decide upon) could be used as default for all output data. Maybe it's too performance heavy though, so maybe it could be a flag or such.

**Comment by borkdude** [comment]
@Saikyun You can print output on multiple lines using `-o`:

```
ls -la | bb -io '(map #(apply str (drop 10 %)) *in*)'
```

**Comment by Saikyun** [comment]
Awesome, thanks! This actually solves a lot of problems. :D

**Comment by borkdude** [comment]
@Saikyun Thanks for the feedback, I'll think about a better way to describe that option. It also works for a single string btw.

**Comment by borkdude** [comment]
@Saikyun Thanks for using babashka btw. Maybe you have some thoughts about this issue? https://github.com/borkdude/babashka/issues/48

**Comment by borkdude** [comment]
Since you can already pprint with [jet](https://github.com/borkdude/jet) I'm closing this for now.

```
$ bb '(range 30)' | jet --pretty
(0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29)
```

**Comment by Saikyun** [comment]
@borkdude I'm happy to try it out. :) I enjoy being able to use clojure in more places.
Ah, didn't know about jet, that's great to know.
It seems like you've already made some decisions wrt #48. I don't know much about spawning processes, so I'd have to play around with it.

**Comment by lvh** [comment]
FWIW one downside to this resolution is that e.g. taoensso.timbre doesn't work (transitive dependency on https://github.com/AvisoNovate/pretty/blob/master/src/io/aviso/exception.clj which in turn specifically wants clojure.pprint).

**Comment by borkdude** [comment]
@lvh I'm not sure what you are referring to, but the latest babashka is now based on clojure.pprint proper. See issue https://github.com/borkdude/babashka/issues/571. What problem are you seeing with 0.2.3?

**Comment by borkdude** [comment]
@lvh Oh I see. That namespace uses `pp/simple-dispatch` which is currently not exposed in bb. Let's make a different issue for that and fix it.

**Comment by sirmspencer** [comment]
Can confrim fipp works great with babashka. https://github.com/brandonbloom/fipp
