### ISSUE TITLE
babashka.edn or .babashka directory with project config

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#473]
Idea: a `babashka.edn` or `.babashka` directory (or both) with a `config.edn` with e.g. a 

- maybe bundle `borkdude.deps` (renaming it to babashka.deps) that picks up deps from babashka.edn (this will require a JVM if .m2 is not populated and the cache is missing, but so will resolving deps using clojure)

- if there is no `babashka.edn` maybe use the `:babashka` alias from `deps.edn`, if there is one? Or configure in babashka.edn which alias to use from deps.edn so you can also put deps in there to avoid duplication?

- `:classpath-cmd` that tells babashka how it should get a classpath for the current directory (project) using some other tool, most often `clojure -Spath`. This command then writes a `.babashka/.cache/classpath-<hash>` where the hash of a number of things like files and environment variables determines what classpath to use (a bit like caching in CI)

- `:classpath-cmd` could also just be git clone + printing a string of the cloned dir for projects that do not have transitive deps, possible done through babashka itself

- Also: `:paths` with just `["src", "test"]`, possibly also just `["."]`. Note: if the file is `.babashka/project.edn` then it might be weird that the paths aren't relative to that file. What about a `babashka.edn` file in the project dir itself? I'm not a big fan of this, since having a `.clj-kondo` directory worked out great for clj-kondo and offered more flexibility. We could just have the convention that `:paths` are relative to the project root and other things might be relative to the `.babashka` dir.

- Configuration of available pod binaries, maybe use the glam logic to fetch them. E.g. if we wanted to have babashka postgres pod, we could write `{:pods {org.babashka/pod-babashka-postgresql {:pod/artifacts {:macos ... :windows ... linux ...}}}`.
And then in babashka itself:

``` clojure
(require '[babashka.pods :as pods])
(pods/load-pod 'org.babashka/pod-babashka-postgresql) ;; symbol means we can look up the binary using config
```

Or maybe (babashka.pods/require 'foo.bar) since a pod management system could also list which namespaces belong to which pods.

We can store the binaries globally or locally, TBD. Locally would mean a nodeJS like approach, globally would require versioning / caching, or maybe just hash the URL where it came from. Or we must keep some repo with available pods like we do in glam.

- We could also support something like boot tasks within babashka.edn or something similar to -X deps.edn.

**Comment by svantevonerichsen6906** [comment]
Consider using the XDG base directory specification for the location of the config directory.

(Yes, Poettering is a co-author, but nevertheless it seems sensible to me.)

**Comment by borkdude** [comment]
@svantevonerichsen6906 It seemse XDG is something system-global, while this is project local, so I don't immediately see how this is applicable?

**Comment by svantevonerichsen6906** [comment]
Ah, sorry, I sloppily misread.  Nevermind.

**Comment by jeroenvandijk** [comment]
An alternative idea of having a `babashka.edn` could be having a babashka function / macro, let says `deps`. 

Typical use would be to put `deps` at the top of a babashka script. In theory you could call it multiple times (I think)

(Stolen from https://github.com/borkdude/babashka#babashkaclasspath)
```clojure
(deps 
   medley {:git/url "https://github.com/borkdude/medley"
           :sha "91adfb5da33f8d23f75f0894da1defe567a625c0"})

(require '[medley.core :as m])
(m/index-by :id [{:id 1} {:id 2}]) ;;=> {1 {:id 1}, 2 {:id 2}}
```
This macro would change the classpath, underneath it could use caching like deps.clj (I'm guessing). And it doesn't have to be a macro if you give `deps` a map with the dependency data.

For (small) scripts, I think I prefer this self-contained inline approach over having two files (the script and babashka.edn)

**Comment by borkdude** [comment]
@jeroenvandijk I think we could do both. Have an API and a `babashka.edn` for "bigger" projects that have multiple entry-points, etc.


Say have a `babashka.deps` API so you can do `(require '[babashka.deps :refer [add-deps])` and then 

```
(add-deps '{weavejester/medley ....})
```

**Comment by lread** [comment]
That is an interesting idea @jeroenvandijk.
Most of my bb scripts make use of local helper namespaces.  

I keep my scripts and helpers under a `scripts` dir, I currently need to effectively

```Clojure
(babashka.classpath/add-classpath "./scripts")
``` 

to allow the local helper namespaces to be be found.

So I'd also need the ability to configure `:paths`. That or maybe have bb default to including the dir of the primary bb script in the classpath?

**Comment by borkdude** [comment]
@lread For your use case I would prefer to have a `babashka.edn` that includes deps and paths.

Would it also be useful to include things from  the regular `deps.edn` (JVM deps) in `babashka.edn`? I'm not sure how much overlap there is between these to worlds within one code-base, so I'm also not sure if we should merge that.

**Comment by jeroenvandijk** [comment]
For @lread 's use case maybe `add-deps` can also be used to add this local dir via `:local/root`? I.e.
```
(add-deps '{me/helpers {:local/root "./scripts"}})
```

**Comment by borkdude** [comment]
@lread's use case is already supported right now via `(babashka.classpath/add-classpath "scripts")`

**Comment by borkdude** [comment]
@lread's use case is already supported right now via `(babashka.classpath/add-classpath "scripts")` 

But he already said that. Maybe the command should be more like the clojure CLI invocation so you can pass in a complete thin with `:deps` and `:paths`, but maybe also pods. Which is basically the `babashka.edn` I was describing in the original post. So you could either stick that in `babashka.edn` or pass in those opts via an API.

**Comment by lread** [comment]
> @lread For your use case I would prefer to have a `babashka.edn` that includes deps and paths.

That would totally work for me!

**Comment by borkdude** [comment]
We could support Jeroen's use case for single scripts without a babashka.edn file using:

``` 
(babashka.deps/init '{...})
```
where init gets the contents of `babashka.edn` inline`. If there is a babashka.edn in the current working dir, then `babashka.deps/init` is automatically called for you.

**Comment by justone** [comment]
I especially appreciate the in-line init call style for standalone scripts.

An additional idea would be to bake in the metadata (name, where to get the binaries, etc) for as many pods as we know of into babashka itself. It can be overridden with the `(babashka.deps/init '{...})` if you need a new pod, but for the most part people can rely on pods that have been around a while.

**Comment by borkdude** [comment]
@justone I was actually considering a git repo with known babashka binaries. When the pod + version + os isn't found in the local checkout of that repo, then the repo will be git pulled to check if there might be newer information.

I've more or less implemented that in this package manager: https://github.com/borkdude/glam

I think the benefit of having it into a separate repo is that it can be easily updated by contributors and can grow without re-installing/updating babashka itself.

**Comment by justone** [comment]
@borkdude Interesting. So when babashka encounters a load-pod call on a fresh system, it will clone that repo and use the metadata to figure out where to download the pod from based on version and platform?

I think this sounds wonderful.

Also, if the metadata repo is public, babashka wouldn't even need to clone it, you can just grab the raw content from github's CDN (assuming it's just one file).

**Comment by borkdude** [comment]
> Also, if the metadata repo is public, babashka wouldn't even need to clone it, you can just grab the raw content from github's CDN (assuming it's just one file).

This is true, but how do you decide that you have the newest?

**Comment by justone** [comment]
Hm, good point. Then with the git method, how do you know you have the newest git content?

It's sort of a cache invalidation problem. The strategy I've taken with similar things in the past is to pull if the data is missing, or if the last pull was more than 24 hours ago. That way I'm not pulling on every run, but the data is kept up to date at some cadence.

**Comment by borkdude** [comment]
> Then with the git method, how do you know you have the newest git content?

- If you have already found the version you want, you don't pull.
- Pull every 24 hours seems like a good default. Could make this overridable in babashka.edn.
- An alternative might be to make the SHA of the babashka pod git repo explicit in babashka.edn, so if you already have that commit, do nothing. This will also allow you to have a predicable set of pod versions.

**Comment by justone** [comment]
Is the `babashka.edn` file that you're talking about somewhere in my homedir, like `~/.clojure/babashka.edn`?

**Comment by borkdude** [comment]
Alternatively we could just leverage deps.edn and have the binary links be part of the pod repos themselves (in a separate branch).

So you would specify those as git deps, they will be pulled using tools.deps and the invocation will be cached, so successive invocations cost almost zero startup time.

> Is the babashka.edn file that you're talking about somewhere in my homedir, like ~/.clojure/babashka.edn?

No, this would be more similar to a deps.edn project file. We could also consider making this part of a deps.edn project file itself, but I'm not so sure about that.

**Comment by justone** [comment]
Ah, so how would `babashka.edn` info work for standalone scripts?

**Comment by borkdude** [comment]
@justone Like in this message: https://github.com/borkdude/babashka/issues/473#issuecomment-735744553

**Comment by borkdude** [comment]
WIP:

``` clojure
(require '[babashka.deps :as deps])
(deps/add-deps '{medley/medley {:mvn/version "1.3.0"}})
;; or should we support passing in `{:deps ...}` so we can also have :paths ["src" "test"]?
;; and what about aliases?
(require '[medley.core :as m])
(m/index-by :id [{:id 1} {:id 2}]) ;; works
```

This now works in the branch babashka-deps.
It shells out to `java` for resolving deps but just like `clojure` it is fast once the classpath is cached.

**Comment by borkdude** [comment]
Should we have another `(deps/add-paths "src" "test")` function as well, or should we just pass in the entire deps.edn-like map? And what about aliases? Maybe `(deps/foobar {:deps {:deps ...} :aliases ["test"]})`, i.e. a programmatic API around processing the deps.edn map?

**Comment by borkdude** [comment]
I'm going to split up the ideas in this issue into multiple smaller issues.

Here are the two under development for the next release:

https://github.com/borkdude/babashka/labels/tools.deps
