### ISSUE TITLE
Consider adding nippy as a built-in library

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#475]
I'm letting this set here to see if there's interest from the community.

One issue:  https://github.com/ptaoussanis/nippy/issues/119

**Comment by borkdude** [comment]
See https://github.com/justone/brisk#babashka-pod-support

**Comment by davesann** [comment]
Am I correct that, as this uses a pod, the data to be written will first be serialised, then de-serialised in the pod, then nippy serialised to a file? (and roughly the reverse for read)

So, while this works, it adds a fair amount of overhead (for larger data). 

Usage for nippy format compatibility, not speed? And if you just want to serialise - something that is in process would likely be better?
