### ISSUE TITLE
Add system property babashka.version which contains current bb version

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#479]
A use case it for people to check a minimum babashka.version. Comparing strings isn't very ergonomic. Should we solve it a different way than with System properties? How can we still preserve compatibility with Clojure by not introducing non-custom vars?

**Comment by borkdude** [comment]
This isn't too bad:

```
(pos? (compare (mapv #(Integer. %) (str/split "0.1.2" #"\.")) [0 1 1]))
true
```

**Comment by borkdude** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add version system property](https://trello.com/c/4DY8OMMU/5-add-version-system-property)

**Comment by jeroenvandijk** [comment]
@borkdude Yeah I think that's perfect for what I had in mind
