### ISSUE TITLE
Clarify:  "Low latency Clojure scripting alternative to JVM Clojure."

### ISSUE THREAD

**Issue by mclillill** [borkdude/babashka#483]
**Is your feature request related to a problem? Please describe.**
In goals it is stated that babashka should be a "Low latency Clojure scripting alternative to JVM Clojure."
What does "low latency" mean in this context? Startup time? If so are you differentiating between first startup and subsequent startups? What is the metric here?

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Not relevant.

**Additional context**
None.

**Comment by borkdude** [comment]
Startup time. Do you think we should just use that term?

**Comment by mclillill** [comment]
@borkdude Hmm... Yes, I think it's probably better since _low latency_ could refer to a lot of things, right?

Additional question: Is _first startup time_ = _subsequent startup time_?

By the way: Awesome project! Thanks for all your efforts and work!

**Comment by borkdude** [comment]
@mclillill The startup time of subsequent runs depends a bit on your OS, processor, etc, because the binary is often cached in memory, but there is no special logic in babashka for subsequent runs. So it's the same compared to most other binaries your run.

**Comment by borkdude** [comment]
@mclillill A PR to reword this is welcome.

**Comment by mclillill** [comment]
@borkdude I will work on this tomorrow.

**Comment by miclill** [comment]
@borkdude See PR #488
