### ISSUE TITLE
`binding` is not working for `clojure.test/report`

### ISSUE THREAD

**Issue by liquidz** [borkdude/babashka#491]
**version**

v0.1.3-SNAPSHOT

**platform**

macOS Catalina

**problem**

`binding` seems not work for `clojure.test/report`

**repro**

```
$ cat foo.clj
(ns foo
  (:require
   [clojure.test :as t]))

(t/deftest bar
  (t/is (= 1 2)))

(binding [t/report println]
  (println "result:"
           (t/test-var #'bar)))
```

```
$ ./bb foo.clj

FAIL in (bar) (/Users/uochan/src/github.com/borkdude/babashka/foo.clj:5)
expected: (= 1 2)
  actual: (not (= 1 2))
result: nil
```

**expected behavior**

```
$ clj -i foo.clj
{:type :begin-test-var, :var #'foo/bar}
{:file foo.clj, :line 6, :type :fail, :expected (= 1 2), :actual (not (= 1 2)), :message nil}
{:type :end-test-var, :var #'foo/bar}
result: nil
```

**Comment by borkdude** [comment]
@liquidz I think I have a fix in the `fix-dynamic-test-report-var` branch. I'll add a test for this tomorrow, but feel free to test it out meanwhile.

**Comment by liquidz** [comment]
@borkdude It works!! (although there is no `:file` and `:line` in the failed report)
Thank you so much for your quick response!

```
$ ./bb foo.clj
{:type :begin-test-var, :var #'foo/bar}
{:type :fail, :expected (= 1 2), :actual (not (= 1 2)), :message nil}
{:type :end-test-var, :var #'foo/bar}
result: nil
```

**Comment by borkdude** [comment]
@liquidz Should be fixed now on master, including `:file` and `:line` (hopefully).

**Comment by liquidz** [comment]
@borkdude Awesome! It works perfectly!!
Thank you so much!

II'll add a test integration on plain nREPL server including Babashka, of course! 
https://github.com/liquidz/vim-iced/pull/227
