### ISSUE TITLE
variable injection?

### ISSUE THREAD

**Issue by maddenp** [borkdude/babashka#493]
**Is your feature request related to a problem? Please describe.**

I've been enjoying working with babashka, especially employing concise one-liners in bash code. One thing I'm having trouble with, though, is getting bash variables into the embedded (via a bash string) Clojure code. In many contexts -- say, an inline `sed` script -- I'd just interpolate the `$variable` into the code, but since double-quotes are needed for Clojure strings, I find myself generally single-quoting the Clojure one-liner I feed to babashka, which inhibits bash variable interpolation. 

**Describe the solution you'd like**

From the ancient to the relatively modern, `awk` and `jq`, whose control inputs are, like `bb` 's, likely to be single-quoted, both provide options to inject variables:

```
% my_variable=foo

% echo bar | awk -v mv=$my_variable '{ print mv }'
foo

% echo '[{"bar": "foo"}, {"bar": "baz"}]' | jq --arg mv $my_variable '.[] | select(.bar == $mv)'
{
  "bar": "foo"
}
```

Assuming I'm not just overlooking an existing, concise-for-one-liners solution with babashka (which I'd be grateful to know about!), would a variable-injection option be possible / desirable?

Alternatively, a concise way to access positional command-line arguments (`$1`, `$2`, etc.?) would work, too, though variable-injection seems me to be less opinionated.

**Describe alternatives you've considered**

I can (and have) escaped the Clojure double quotes to permit outer double quotes, but that's a little ugly. I've tried passing variables as command-line arguments, but `*command-line-args*` is a bit unwieldy in a one-liner. Maybe I could use environment variable, but I don't think that's going to be concise, either.

Thanks for the amazing babashka, by the way!

**Comment by borkdude** [comment]
@maddenp Have you considered writing a function or macro in your `BABASHKA_PRELOADS`?

```
export BABASHKA_PRELOADS="(defmacro $ [x] \`(System/getenv ~(str x)))"
$ bb '(-> ($ PWD) (str/split #"/") last)'
"clj-kondo"
```

**Comment by maddenp** [comment]
I did not think of that, but it's a great idea and concisely solves my problem. Thank you.

**Comment by borkdude** [comment]
You're welcome.

Another variation:

```
export BABASHKA_PRELOADS="(doseq [[k v] (System/getenv)] (intern *ns* (symbol k) v))"

$ ( cd ~; bb '(= HOME PWD)')
true
```
