### ISSUE TITLE
add clojure.java.browse/browse-url

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#495]
As discussed on Slack:

@lread I would be open to a PR that adds clojure.java.browse/browse-url, but only shells out and doesn't use the reflection or swing stuff. (edited) 
So our own stripped down implementation of it.

**Comment by lread** [comment]
A note from lukasz on Slack:

@lread FWIW - open and xdg-open do all of this for you in OSX and Linux respectively, so could be just a one-liner. No idea about Windows

**Comment by borkdude** [comment]
The Windows equivalent of open/xdg-open is probably start on Windows. The clojure.java.browse namespace has also some logic for Cygwin, but I'm not sure how relevant this is.
