### ISSUE TITLE
Use namespace keyword for reader conditionals

### ISSUE THREAD

**Issue by AndreTheHunter** [borkdude/babashka#497]
**Is your feature request related to a problem? Please describe.**
The [Clojure reference ](https://clojure.org/reference/reader#_reader_conditionals) states that non official platforms should use namespaces keywords.
> Implementors of non-official Clojure platforms should use a qualified keyword for their platform feature to avoid name collisions. Unqualified platform features are reserved for official platforms.

**Describe the solution you'd like**
Change `:bb` reader conditional. Something like `:borkdudde/bb`

**Describe alternatives you've considered**
... or don't change it. Just thought I'd let you know 😁

**Additional context**
Nope

**Comment by borkdude** [comment]
I won't change this, as this was already part of babashka before those docs changed (it was changed after a conversation I had with Alex Miller in Clojurians Slack). Too late. For newer "languages" I would adhere to the new recommendation, but I'm not going to make any breaking changes.
