### ISSUE TITLE
Unexpected behaviour: -f with empty script starts repl

### ISSUE THREAD

**Issue by jeroenvandijk** [borkdude/babashka#498]
**version**

babashka v0.1.2 and below

**platform**

Mac, Linux

**problem**

Babashka starts a repl when the script it is given is empty.

**repro**

```
echo '(println "hi")' > empty.txt
 bb -f empty.txt
hi
```

vs  
```
touch empty.txt
 bb -f empty.txt
Babashka v0.1.2 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=>
```

**expected behavior**

I'm expecting that `bb` either complains about the empty file OR just does nothing, but not that it starts the repl. It gives me doubts about whether I'm using the right cli option (-f)

**Comment by borkdude** [comment]
Doing nothing makes sense. I think the cause of this is that there's some code in main.clj which checks if the program is empty and if so it starts the REPL.:

https://github.com/borkdude/babashka/blob/633264096dcb1aa0744cad71f1527275b37325c7/src/babashka/main.clj#L544
