### ISSUE TITLE
What is approx. compile time for bb using graal?

### ISSUE THREAD

**Issue by samirsa** [borkdude/babashka#504]
Thanks for making babashka. I think it is really awesome. 

Sorry, if this is not the right place to ask this question, but what is the approx. compile time?
I needed to compile with jdbc support and set the corresponding JDBC and postgres flags.

Here is the output. Are these kind of messages and compile times normal?

[bb:18327]    classlist:   3,530.53 ms,  0.96 GB
[bb:18327]        (cap):   1,804.86 ms,  0.96 GB
[bb:18327]        setup:   3,331.98 ms,  0.96 GB
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:28] scope: ForkJoinPool-4-worker-19
  [thread:28] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
  [thread:28] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/com.fasterxml.jackson.core.JsonFactory
  [thread:28] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.sql.Driver
  [thread:28] scope: ForkJoinPool-4-worker-19.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
Exception in thread "Libgraal MBean Registration" java.lang.OutOfMemoryError: GC overhead limit exceeded
[bb:18327]     analysis: 2,836,654.44 ms,  4.17 GB

I am new to the whole Graal thing, so maybe I am missing something. I do know that Graal compile times can be quite slow. but this is reaching ~45 minutes? And the activity monitor (doing this on mac osx) continuously showed the java process at 900-1000% of CPU. 

The following is not related to my question, but just thought of letting you know in case it is something which needs to be fixed. 
I set the LEAN flag, to see if the compile was any faster - but got an exception. 

➜  babashka git:(master) script/uberjar
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Syntax error (ClassNotFoundException) compiling at (/private/var/folders/zj/qb5ctrb51nbdwl47kqrn7yrr0000gn/T/form-init17339255376866517147.clj:1:126).
org.yaml.snakeyaml.error.YAMLException

**Comment by borkdude** [comment]
@samirsa It should not be 45 minutes, more in the ballpark of 5-10 minutes. Have you tried setting the -Xmx value higher with `BABASHKA_XMX=-J-Xmx7000m` for example?

I'll look into the LEAN flag issue. Thanks for reporting.

**Comment by borkdude** [comment]
@samirsa Another tip btw, have you seen https://github.com/babashka/babashka-sql-pods? This doesn't require compilation, you can just install the pod and have postgres queries work that way.

**Comment by samirsa** [comment]
Thanks for the quick response. I had just set it to 4800m as per the build.md page, but I guess that was not enough. Setting it to 16384m bought the compile time down to 3 minutes!

Also, thanks for the update on the pods. I remember reading about them earlier, but forgot about them. I guess the jdbc/sql pod was not needed for the older version, but is now. So, the script stopped working. I saw in the readme about requiring a Graal build if one wants jdbc support, and so went down that path.

Maybe a small snippet in the readme, that building is not required for sql support would be helpful?

Thanks again for this. BB is really an awesome little thing (though the size now is at 100M!) but frank enough that is a small price to pay to get all the clojure goodness in a shell-like language.

**Comment by borkdude** [comment]
@samirsa Fixed `BABASHKA_LEAN` with 227b8a0e7743e6074a89cc0ba6112a06c758b02a.

On my laptop OS, macOS Mojave, I'm getting 47MB for the lean build and 64MB for the normal build. In the past, when incorporating the Postgres driver, it added only 3MB or so, so that would be 67MB in total. Where do you get 100MB, that doesn't sound entirely right.

> Maybe a small snippet in the readme, that building is not required for sql support would be helpful?

Yes, I'll add the snippet. Thanks for the feedback.
