### ISSUE TITLE
Babashka shows wrong filename when error is from required ns

### ISSUE THREAD

**Issue by lread** [borkdude/babashka#508]
**version**
babashka v0.1.3

**platform**
macOS 10.15.5

**symptom**
An exception thrown from a required namespace shows the filename of the entry namespace.

**repro**
Given two source files in the same directory:

`main.clj`
```Clojure
(ns main
  (:require [babashka.classpath :as cp]))

(cp/add-classpath ".")

(require '[other :as other])

(println "call ok - does not throw")
(other/ok)

(println "\ncall uh-oh - intentionally throws")
(other/uh-oh)
```

`other.clj`
```Clojure
(ns other)

(defn ok []
  "ok")

(defn uh-oh []
  (/ 1 0))
```

Run:
```
bb main.clj
```

**actual behavior**
The correct `line` and `column` are reported, but the wrong filename is reported.
```
call ok - does not throw

call uh-oh - intentionally throws
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/play/bb-wrong-filename/main.clj, line 7, column 3]
```

**expected behavior**
```
call ok - does not throw

call uh-oh - intentionally throws
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/play/bb-wrong-filename/other.clj, line 7, column 3]
```

**Comment by borkdude** [comment]
@lread Thanks for the report. There is a preliminary fix in branch `issue-508`.

**Comment by borkdude** [comment]
Not sure if and how the solution works out in general, so some testing would be appreciated.

**Comment by borkdude** [comment]
Note to self: the current solution reads the `:file` metadata of the invoked var and places it onto a callstack vector.  This is then used in error message. A cleaner solution would be to attach also the `:file` metadata during read time. 

Explanation: Clojure retrieves this information from the stacktrace, but SCI this doesn't work, since the JVM stacktrace only contains information from the interpreter code and not from the _interpreted_ code.

**Comment by lread** [comment]
@borkdude, I tried issue-508 branch with my repro scenario and don't see any difference.

Tried via jvm:
```
> clojure -m babashka.main --version      
babashka v0.1.4-SNAPSHOT
> clojure -m babashka.main main.clj 
call ok - does not throw

call uh-oh - intentionally throws
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/babashka/main.clj, line 7, column 3]
```
And compiled bb:
```
> ./bb --version
babashka v0.1.4-SNAPSHOT
> ./bb main.clj
call ok - does not throw

call uh-oh - intentionally throws
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/babashka/main.clj, line 7, column 3]
```

**Comment by borkdude** [comment]
@lread That's odd. Is the sci git module checked out at commit `72beee9faceb401ec5bc00f7752c91fafdfa0c4b`?

**Comment by lread** [comment]
Aha... my bad.  
```
> git submodule update --recursive
Submodule path 'sci': checked out '72beee9faceb401ec5bc00f7752c91fafdfa0c4b'
```
I now see your fix works for my repro case:
```
> clojure -m babashka.main main.clj 
call ok - does not throw

call uh-oh - intentionally throws
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/babashka/other.clj, line 7, column 3]
```
I'll try a few more tests.

**Comment by lread** [comment]
I'm not sure what to test, so I'll go for some minimal black box testing... each test marked with SUCCESS or FAIL.  These might ( or might not  🙂) help you to think of other scenarios to try.

**FAIL - preload from eval**

`preloadtest.clj`
```Clojure
(ns preloadtest)

(user/ithrow)
```

Run from bash:
```
BABASHKA_PRELOADS='(defn ithrow [] (/ 1 0))'
export BABASHKA_PRELOADS 
clojure -m babashka.main preloadtest.clj
```
Results in correct `line` and `row` but misleads with filename:
```
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/babashka/preloadtest.clj, line 1, column 17]
```


**SUCCESS - preload from file**

`ithrow.clj`
```Clojure
(defn ithrow
  "intentionally cause exception"
  []
  (/ 1 0))
```

Run from bash:
```
BABASHKA_PRELOADS='(load-file "ithrow.clj")'
export BABASHKA_PRELOADS 
clojure -m babashka.main preloadtest.clj
```
Gives expected output:
```
java.lang.ArithmeticException: Divide by zero [at /Users/lee/proj/oss/babashka/ithrow.clj, line 4, column 3]
```

**SUCCESS - command line classpath to gist**
My original repro used `babashka.classpath/add-classpath`, let's try a command line classpath that points to [a gist](https://gist.github.com/lread/b810e67e71368a95caf3b24f95b842d1).

`cptest.clj`
```Clojure
(ns cptest
  (:require [ithrow]))

(ithrow/ithrow-too)
```

Run from bash:
```
clojure -m babashka.main --classpath $(clojure -Spath -Sdeps '{:deps {mygist {:git/url "https://gist.github.com/lread/b810e67e71368a95caf3b24f95b842d1" :sha "5718de06536b83f0f4f8eedec1728f80e17a0a9e"}}}') cptest.clj
```
Gives expected output:
```
clojure.lang.ExceptionInfo: Blarp! [at /Users/lee/.gitlibs/libs/mygist/mygist/5718de06536b83f0f4f8eedec1728f80e17a0a9e/ithrow.clj, line 4, column 3]
```

**Comment by borkdude** [comment]
@lread Pushed a fix for the `BABASHKA_PRELOADS` location in 649ed323660a47cdd54c4ab8275b16800e8b9ef8

**Comment by borkdude** [comment]
@lread Should finally be fixed now on master. Will be released soon, I hope.
