### ISSUE TITLE
Brew install fails on Mac with SHA256 mismatch

### ISSUE THREAD

**Issue by yurist** [borkdude/babashka#509]
**version**

N/A can't install

**platform**

MacOS Catalina 10.15, brew 2.4.6

**problem**

Installation fails

==> Installing babashka from borkdude/brew
==> Downloading https://github.com/borkdude/babashka/releases/download/v0.1.3/babashka-0.1.3-macos-amd64.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/201467090/cd6ab780-b87c-11ea-9d26-79b602c8df43?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential
                                               -=O=-                      # ##
Error: SHA256 mismatch
Expected: e78602a9d1e37e6048f4c9e83b48248b03829a8bb8deb3036cc8743c6f2d37f5
  Actual: 0097dcb7ce68bdda42f6fd216e29795ad2c83469f73fa58c50146a76972b54c7

**repro**

Does it work for you?

**expected behavior**

Installs

**Comment by borkdude** [comment]
@yurist Strangely I can't reproduce this:

```
$ brew install borkdude/brew/babashka
==> Installing babashka from borkdude/brew
==> Downloading https://github.com/borkdude/babashka/releases/download/v0.1.3/babashka-0.1.3-macos-amd64.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/201467090/cd6ab780-b87c-11ea-9d26-79b602c8df43?X-Amz-Algorithm=AWS4-HMAC-SHA256&X
######################################################################## 100.0%
🍺  /usr/local/Cellar/babashka/0.1.3: 3 files, 60.8MB, built in 3 seconds
```

I'm also on Catalina and using brew 2.4.6 as well.

**Comment by yurist** [comment]
@borkdude thanks a ton for a super-quick response. I removed the archive and tried again to no avail. But regardless, good to know it works for you, so no problem with the binaries themselves. Will install outside of brew. Cheers!

**Comment by yurist** [comment]
Figured it out - a weird effect of http proxy.
