### ISSUE TITLE
Adding clojure.data.zip?

### ISSUE THREAD

**Issue by MrGung** [borkdude/babashka#513]
I cannot put my head around processing XML with zippers. 

Having clojure.data.zip available would greatly increase babashka's utility (for me).

Could it be added - or could it somehow be imported (I am relatively new to babashka).

**Comment by borkdude** [comment]
Yep, checkout the libraries.md page:

https://github.com/borkdude/babashka/blob/master/doc/libraries.md#clojuredatazip
