### ISSUE TITLE
Help with compiling Jep to native image

### ISSUE THREAD

**Issue by zcaudate** [borkdude/babashka#517]
I'd like to get some help compiling [jep](https://github.com/ninia/jep) (an embedded python runtime) to native image. It builds to a native image but then [errors](https://github.com/oracle/graal/issues/2724) when the binary is run. 

I'm hoping it's an easy issue that people with more experience in graal can solve. The sample repo is [here](https://github.com/zcaudate/sample-jep-graal).

**Comment by borkdude** [comment]
This is not a general "I want help with GraalVM" repo. 
You can use these resources for that:
- Clojurians Slack, the #graalvm channel
- GraalVM slack: https://app.slack.com/client/TN37RDLPK/CN9KSFB40
- https://github.com/lread/clj-graal-docs/
- https://github.com/BrunoBonacci/graalvm-clojure

**Comment by zcaudate** [comment]
Sorry.

I just thought that it's something that babashka can integrate with if it the pathway gets resolved. I'm happy using the lib on jvm but would be ecstatic if the start up time is gone.

Given that the defacto python interop `libpython-clj` is using JNA and so be harder to compile natively, it's a really good option for no-copy memory access of Clojure data using python libraries.

I'll also ask in those places as well. Thanks!
