### ISSUE TITLE
Simplify interaction with processes!

### ISSUE THREAD

**Issue by aadrian** [borkdude/babashka#521]
Please simplify the interaction with processes from BB, since this is one of the main use cases.

Having to use ProcessBuilder (API) directly is just a plain PITA _(in Java or in any other language that exposes that API as it is)_.

I'm aware of the detailed documentation: https://book.babashka.org/#_java_lang_processbuilder - it's just fantastic that it's explained with that much detail.

Thanks in advance,

**Comment by borkdude** [comment]
@aadrian Apart from `clojure.java.shell/sh` what simplification would you like to see around using ProcessBuilder? What is wrong with creating your own functions based on ProcessBuilder and using those? Like this: https://github.com/lambdaisland/open-source/blob/master/src/lioss/subshell.clj

**Comment by borkdude** [comment]
@aadrian I whipped something together here:

https://github.com/babashka/babashka.process

Feedback is welcome.

**Comment by aadrian** [comment]
@borkdude wow, this looks very nice and also "clojure like" :D .

----

Maybe a few use cases that one could typically "control", and automate (maybe with BB?) :
 - list files, owner, rights, other attributes etc.
 - diff/compare, calculate hashes, watch for changes
 - list processes
 - list occupied ports (and their process)
 - list open connections, IPs
 - compare connection IPs to whitelists/blacklists, etc.
 - manage processes and process trees (start, watch, attach to running processes, nice, ionice,  kill, etc)
 - manage services, manage cronjobs, (check if cronjob still runs, check if some services run, restart/kill ,etc.)
 - get resource usage (cpu/mem/swap/io)
 - interact with packages (apt, yum, rpm)
 - tail log files (notify on patterns, etc.)

I'm aware of Spire https://github.com/epiccastle/spire , it is very nice _(but unfortunately it just seems to try to copy Ansible for now)_

Considering that Clojure offers `core.logic` and many other very nice things (that are harder to use in other languages), with the help of BB scripting, this could open some very nice "smart" automation and resource management possibilities :) .

**Comment by grzm** [comment]
I'm really liking the look of babashka.process. Thanks, @borkdude ! As for the addition features listed in https://github.com/borkdude/babashka/issues/521#issuecomment-670680520, those seem to be a great set of features for a library, as opposed to something directly baked into either babashka or as part of babashka.process. Lots of likely differing opinions on how one might want to expose those features. I've really started to embrace using setting `bb --classpath` via `$(clojure -A:some-alias -Spath)` and an appropriate `deps.edn`: including libraries is really easy. Well-factored, composable tools! :) What's not to love? ❤️

**Comment by borkdude** [comment]
Fixed with the inclusion of https://github.com/babashka/process
