### ISSUE TITLE
Consider adding http-kit server

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#556]
As of version `[http-kit "2.5.0-alpha2"]` [http-kit](https://github.com/http-kit/http-kit) is compatible with GraalVM. In the `http-kit` branch we added the `org.httpkit.server` namespace (only the `run-server` function) and it results in only a 0.5MB increase in binary size, which seems very reasonable. Adding a web-server to babashka could be useful for small apps. Some babashka scripts have their own implementation of an http server, see examples/notes, examples/http-server and https://github.com/djblue/portal. Including a built-in webserver could make writing these apps easier, but isn't a full solution. Adding this would probably also lead to adding a routing library (compojure, reitit, etc) and perhaps more? Another idea is to implement it as a pod first.

Example:

``` clojure
(require '[org.httpkit.server :as srv]
         '[clojure.java.browse :as browse])

(defn app [{:keys [:request-method :uri]}]
  (case [request-method uri]
    [:get "/"] {:body "Welcome!"
                :status 200}
    [:get "/foo"] {:body "Foo!"
                   :status 200}))

(srv/run-server app {:port 8080})

(println "8080")
(browse/browse-url "http://localhost:8080")

@(promise)
```

![Screenshot 2020-08-29 at 15 04 56](https://user-images.githubusercontent.com/284934/91637606-f557d200-ea09-11ea-9533-2b5d58d6940b.png)

Linux binary: https://11364-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.1-SNAPSHOT-linux-amd64.zip
macOS binary: https://11363-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.1-SNAPSHOT-macos-amd64.zip
Windows binary: https://ci.appveyor.com/api/buildjobs/lif2y7lee7sqwkpc/artifacts/babashka-0.2.1-SNAPSHOT-windows-amd64.zip

Please let me know if you would find this useful and how you would use this.

**Comment by jcooley** [comment]
Nice idea. It could open up a whole set of nice services, similar to https://github.com/beefsack/webify.

SSL support would be nice (grabbing a cert from the local nginx server or some other source).

**Comment by jeroenvandijk** [comment]
**Example usecase webserver**
A local webserver is necessary for cli apps that want to get credentials via an oauth/openid flow. The flow is open a webbrowser: `localhost` -> `authentication-endpoint` -> `localhost?token=<credential-token-here>`. The token is used to do an exchange for full credentials. This also requires SSL support (https).

Examples of authentication endpoints are google oauth, AWS cognito (to get AWS temporary credentials).

**Comment by onetom** [comment]
For SSL support, I would just add a https://caddyserver.com/ in front of my Babashka HTTP server.
I was also experimenting with just using CGI, whenever I need some development web-server on top of some simple scripts written in... whatever language :)
Unfortunately I haven't found any simple, minimalistic CGI servers, so I've settled with using the CGI support built in to the Python 2/3 HTTP libs via the following compatibility `cgi-server.sh` script:

```
#!/usr/bin/env bash

# python -m webbrowser http://localhost:2019

if (python --version | grep 'Python 2'); then
    python -m CGIHTTPServer 2019
else
    python -m http.server --cgi 2019
fi
```

then I can combine it with static file serving using https://github.com/cortesi/devd via https://github.com/cortesi/modd , using the following `modd.conf`:

```
{
    daemon: ./cgi-server.sh
}

*.html {
    daemon: devd --all --open --modd http://localhost:2019
}
```

then I would have a hot-reloading web development environment, where the program I need to write only deals with stdin (for POST requests), environment vars for HTTP headers and stdout for HTTP replies.

Caddy also has CGI support, just not by default, but if you don't mind getting a custom compiled version for your specific OS, then that's also a great choice.

I'm aware of many other CGI capable, tiny web-servers, like light-httpd, mini_httpd, but they are mostly Linux-only, have quircky config file formats or just hasn't been packaged up in Nixpkgs for both Linux and macOS.

**Comment by kloimhardt** [comment]
I think a highly opinionated mini web-framework based on Babashka/SCI can make sense, because of: 

- no install process but full MS-Windows(TM) support (which allows quick sketching/hand-over of localhost web-apps on corporate Laptops using Notepad++ editor, no Admin rights necessary)
- fast startup (for restarting the web-server because the user has not yet learned REPL+intengrant/mount/etc.)
- runs both as executable and in browser (same language in front-end (without compile step, avoids confusing possible stale code) and back-end)
- good error messages (to easily find out what is going on in the back-end when pressing a button in the browser and nothing works)
- discussions about choices for libraries (e.g. router) can be held short with the argument that the user will not know the difference and Web-Babashka leads to Clojure+Clojurescript after the initial App-idea makes sense and then the user has learned about REPL, Integrant, hot-relaoding, Figwheel/ShadowCLJS, different router libraries, etc.

**Comment by borkdude** [comment]
As for the opinionated set of libraries, we could also re-introduce jdbc.next + postgres support.

**Comment by jeroenvandijk** [comment]
What about somehow supporting https://github.com/alekcz/pcp/ (via a pod?) instead of copying that functionality?

**Comment by borkdude** [comment]
@jeroenvandijk This issue isn't about implement a web framework like PCP, only about making such a thing possible by providing the necessary parts.

**Comment by kloimhardt** [comment]
I made a 50 line mini-nano web framework to show and explain further why I think it can make sense to add http-kit: https://github.com/kloimhardt/bb-web

**Comment by borkdude** [comment]
@kloimhardt I only see a hot-reload button and the rest of the screen is blank.

**Comment by kloimhardt** [comment]
@borkdude After pressing hot-reload, two more buttons should appear. Do you see them? I realise it is bad design, I will change it.

**Comment by borkdude** [comment]
@kloimhardt I did try that, but nothing happened.

**Comment by kloimhardt** [comment]
@borkdude Oh, then the redesign I just made will not help I suspect (although I have an unjustified hope). By tomorrow I'll have the repo cloned on another computer to find out what's going on. Maybe I have some crucial file locally which I am not aware of.

**Comment by kloimhardt** [comment]
@borkdude I tried on Mac and Windows, the click-me-to-count button showed up and worked as canonically expected. Chrome devtools complain on the console though. I'll look into that.

**Comment by borkdude** [comment]
@kloimhardt I think I know what's wrong. I tried to change the port in server.clj since port 8000 is already taken on my machine. But it seems that in the JS assets there is a port number hardcoded in it.

**Comment by borkdude** [comment]
@kloimhardt Now it worked, when I shutdown the process on port 8000. Nice one :)

**Comment by kloimhardt** [comment]
@borkdude Indeed, 8000 is hardcoded at the moment. Thank you for having a look despite this inconvenience.

**Comment by borkdude** [comment]
If we are going to focus on small web-apps, maybe geared towards beginner experience, maybe including compojure for routing is the most light weight thing?

**Comment by kloimhardt** [comment]
Arguably, the Luminus book will be the probable next step for a Babashka-app developer starting out on his own. Aligning the choices with chapter two of the Luminus book (3rd edition) is psychologically profitable for a beginner (I am not able to make any technical argument on Reitit vs. Compojure)

**Comment by kloimhardt** [comment]
I have a dream: the Luminus people allow modification of their chapter two to work with this spin-off and give it away for free. I think the discussions about a Clojure web-stack would reduce to 10% volume.

I think the baggage (and work for a spin off) is only worth it with free and detailed documentation like this excellent chapter two which would occupy a beginner for month and get him a very long way.

**Comment by borkdude** [comment]
I think for babashka it's best to focus on scripting utility: so let's get back to the discussion of what an http-server would add for a scripting utility.

**Comment by dharrigan** [comment]
I would greatly welcome adding the ability to quickly fire up a little http server with Babashka - there are many use cases where that would come in very handy, without resorting to other tooling. Take for instance the ability to fire up a very simple proxy that simply receives anything given to it and prints it out on the console - a great tool for debugging APIs.

Or, being able to fire up a quick server that can serve up some content (say a file, or directory) that you can tell your other colleagues about, to quickly and easily share some content across the LAN.

I think having a built-in http-server would open up more possibilities for showcasing what Babashka can do!

**Comment by borkdude** [comment]
@dharrigan 

Do you think httpkit server would be valuable without a routing library, or do we need to make a choice here?
Btw, you can already try out a bb build with httpkit server (and client) built in (see top post).

**Comment by dharrigan** [comment]
Not sure. The example given on the OP would cater for my needs in that my routes would be very simple. I can define a GET, POST etc., a path and a function to call when invoked. Would a routing library be required to handle other scenarios, such as routing based upon values, .e.g, `"/{id}"`?

**Comment by borkdude** [comment]
@dharrigan I guess parsing a route like that yourself isn't that hard. 

Btw, there are also exiting possibilities of running a tiny webserver in bb already. The examples dir has a notes app and a http file browser. But it's hand-written, you even have to parse the HTTP headers yourself, which is tedious for little apps like that.

If we end up adding a router library, it will be an opinionated thing: some people like Reitit, other people like Compojure, etc.
And where does it end: do we need to add hiccup, etc. too? (The notes app has a very simple hiccup implementation in a few lines of code).

**Comment by dharrigan** [comment]
For what it's worth, I use reitit and like it :-)

As the author of babashka, you can call where it ends :-)

**Comment by borkdude** [comment]
I really just wonder if adding only an HTTP server without a full stack web solution will put people off, or will lead people to demand this to become that thing, or if people find it already useful with minimal web tooling.

Same thing when I added the Postgres JDBC driver: people starting asking for mySQL, etc. etc. I shortly moved the Postgres driver to a feature flag after, since I can't really support all the databases (factoring in GraalVM native-image compatibility, memory limits on CI, binary size growth, etc).

**Comment by dharrigan** [comment]
That's a very good and valid point. If in doubt, do nothing - leave it off? Babashka is totally awesome and useful as it is anyhow :)

**Comment by borkdude** [comment]
@dharrigan One idea to try out new libs and to what people are doing with them:

https://github.com/borkdude/babashka/issues/573

Using these new namespaces will print a warning with a link to an issue where people can post feedback why they'd like to keep that feature.

Same for things that might be removed (I have nothing in mind at the moment, but maybe over time some things will replace others).

**Comment by dharrigan** [comment]
That would be a nice idea. Put it in, gather feedback on it, then decide if to make it a permanent feature.

**Comment by borkdude** [comment]
On master:

``` 
$ bb -e "(require '[org.httpkit.server :as srv]) (srv/run-server (fn [_] {:body \"Hello\"}) {:port 8088}) @(promise)"
WARNING: the org.httpkit.server namespace is experimental and may be removed in future versions of babashka.
Please leave a note at https://github.com/borkdude/babashka/issues/556 to let us know how you are using it.
You can turn this warning off using -Dbabashka.httpkit-server.warning=false
This namespace will remain available under a feature flag, see https://github.com/borkdude/babashka/blob/master/doc/build.md#feature-flags
``` 

To turn off the warning:

``` 
$ bb -Dbabashka.httpkit-server.warning=false -e "(require '[org.httpkit.server :as srv]) (srv/run-server (fn [_] {:body \"Hello\"}) {:port 8088}) @(promise)"
``` 

or

``` 
bb -e "(binding [*err* (java.io.StringWriter.)] (require '[org.httpkit.server :as srv])) (srv/run-server (fn [_] {:body \"Hello\"}) {:port 8088}) @(promise)"
``` 

You can find binaries via the CircleCI or Github artifacts or in the babashka_circleci_builds channel on Clojurians slack.

**Comment by davidpham87** [comment]
Following our conversation on Slack, I just wanted to share that I find the server really useful, I hope to replace my actual nodejs/cljs code with it, the main use case would be to perform some tasks on the server when using git hooks or other processes.

I also asked whether reitit as a router would be usable with basbashka to get some routing, and I wonder what the community think about that.

**Comment by borkdude** [comment]
Bootleg is a nice utility that can be used from babashka in combination with the server:

https://github.com/retrogradeorbit/bootleg

``` 
(ns mybbscript
  (:require [babashka.pods :as pods]
            [org.httpkit.server :as srv]))

(pods/load-pod "bootleg")
(require '[pod.retrogradeorbit.bootleg.utils :as utils])

(def page
  (-> [:div
       [:h1 "Serving HTML using bootleg and babashka's httpkit server!"]
       [:p "Yay."]]
      (utils/convert-to :html)))

(srv/run-server (fn [_] {:body page})
                {:port 8080})

@(promise)
``` 

<img width="866" alt="Screenshot 2020-09-30 at 23 10 59" src="https://user-images.githubusercontent.com/284934/94740137-645e7880-0372-11eb-9eab-fece1e74483a.png">

**Comment by borkdude** [comment]
Someone in the Clojurians Slack channel today suggested that the server can also be used to implement Oauth.

**Comment by borkdude** [comment]
Portal uses the httpkit server for the JVM and babashka: https://github.com/djblue/portal

**Comment by borkdude** [comment]
After having seen the demo by @djblue at https://www.youtube.com/watch?v=gByyg-m0XOg&ab_channel=aproposclojure I no longer have doubts that including the server isn't a good fit for bb. I'll remove the warning you are getting on require in 0.2.3.

**Comment by borkdude** [comment]
Another useful thing I did with the server: https://twitter.com/borkdude/status/1320134220107419648

https://github.com/borkdude/babashka/tree/master/examples#image-viewer
