### ISSUE TITLE
Who is using core.async and how?

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#559]
I'd like to get an idea if and how many people are using core.async and how they are using it. Please leave a note here.

Right now we only support thread operations (double exclamation marks). The go block and single exclamation mark operations are mapped to the fully threaded operations, just for compatibility. This is documented in the README.

To make go work like it does on the JVM, we need to re-implement parts of tools.analyzer, which will take a lot of time.

We could either leave this as a documented difference, remove go or remove core.async entirely.

Some resources on the go macro:

- https://www.youtube.com/watch?v=R3PZMIwXN_g
- https://www.youtube.com/watch?v=SI7qtuuahhU

**Comment by rschmukler** [comment]
Just a note that loom is also relatively near on the horizon. I'm not sure how (or if) Graal will handle continuations, but it's worth considering the possible deprecation in utility of `core.async`'s parking semantics if the JVM ends up handling it anyway. Just something to consider while balancing the engineering required to bring full-on `go` support.

**Comment by mk** [comment]
> The go block and single exclamation mark operations are mapped to the fully threaded operations, just for compatibility.

I think this is reasonable and preferred to not support `go` at all.

> Just a note that loom is also relatively near on the horizon.
@rschmukler what does that mean exactly? I'm excited about loom but can't find the info which JDK they will target. I thought it wasn't decided, yet.

**Comment by borkdude** [comment]
@mk Thanks for the sponsorship btw.

**Comment by borkdude** [comment]
I added this to the README:

- Managing expectations: https://github.com/borkdude/babashka#managing-expectations. This text was already in the README but I've now made it more prominent. This text links to:
- Differences with Clojure: https://github.com/borkdude/babashka#differences-with-clojure, which links to:
- An example that shows where mapping go to thread may break down for a high number of threads, [here](https://github.com/borkdude/babashka#coreasync)
