### ISSUE TITLE
revisit clojure.pprint

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#571]
Clojure.pprint is currently based on fipp, because that worked better with GraalVM. We might revisit this to base it on the true pprint and also add cl-format.

**Comment by borkdude** [comment]
Probably looking at CLJS pprint will be helpful. Maybe that's easier to get GraalVM compatible.

https://github.com/clojure/clojurescript/blob/r1.10.773-2-g946348da/src/main/cljs/cljs/pprint.cljs

**Comment by borkdude** [comment]
@tylerw `cl-format` should be included in these binaries:

- macOS: https://11973-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.1-SNAPSHOT-macos-amd64.zip
- linux: https://11971-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.1-SNAPSHOT-linux-amd64.zip

Could you give it some testing?

**Comment by tylerw** [comment]
This is great! I've exercised it with several format directives and haven't encountered a discrepancy yet. I'll continue to test it over the next few days.

**Comment by borkdude** [comment]
@tylerw Merged to master. New binaries can also be found by clicking on the green checkmark and then navigating to artifacts.
