### ISSUE TITLE
Consider adding support for clojure.pprint/cl-format

### ISSUE THREAD

**Issue by tylerw** [borkdude/babashka#578]
The cl-format function, which is the Clojure equivalent to Common Lisp's FORMAT, has facilities for handling lists/seqs, which is often very helpful in Lisp. This need not be built in to the default distribution, e.g., it could work as a pod (if technically feasible).

Currently babashba uses fipp for pretty printing, which does not have cl-format.

**Comment by borkdude** [comment]
See #571

**Comment by tylerw** [comment]
Thanks, I missed that. I'll close this issue out.
