### ISSUE TITLE
sending mail: include lib or make pod

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#599]
Since an email is just plain data, it's a perfect candidate for a pod.
E.g. drewr/postal could be compiled with GraalVM java 8 and then be used from babashka.
Note that we have tried to use drewr/postal before, but this failed due to Java 11 restrictions:
https://github.com/borkdude/babashka/issues/366
Worked around that (https://github.com/drewr/postal/issues/107), now running into:

> javax.activation.UnsupportedDataTypeException: no object DCH for MIME type text/plain; charset=utf-8

``` 
$ rlwrap ./bb
Babashka v0.2.2-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[postal.core :as p])
nil
user=> (p/send-message {} {:from "michielborkent@gmail.com" :to "michielborkent@gmail.com" :body "hello"})
javax.activation.UnsupportedDataTypeException: no object DCH for MIME type text/plain; charset=utf-8 [at <repl>:2:1]
``` 

Seems to be the same issue as in: https://github.com/quarkusio/quarkus/issues/1840
Work in progress in branch https://github.com/borkdude/babashka/tree/postal2.

Maybe this Quarkus extension could be wrapped in some Clojure code:
https://github.com/quarkusio/quarkus/tree/master/extensions/mailer
But that wouldn't be the same as postal

More info: https://github.com/babashka/babashka.pods
https://github.com/borkdude/babashka/blob/master/doc/libraries.md#pods 

Another lib in this space: https://github.com/toyokumo/tarayo

**Comment by borkdude** [comment]
Here is a fix for Java 11: https://github.com/drewr/postal/issues/107

**Comment by borkdude** [comment]
Another lib in this space: https://github.com/toyokumo/tarayo

**Comment by borkdude** [comment]
There's now a pod available: https://github.com/tzzh/pod-tzzh-mail

**Comment by borkdude** [comment]
If anyone knows how to make postal to work with GraalVM, I'm willing to take another look.

**Comment by drewr** [comment]
Thank you for writing this up @borkdude!
