### ISSUE TITLE
macro lazy-cat is not defined

### ISSUE THREAD

**Issue by randomizedthinking** [borkdude/babashka#605]
**Is your feature request related to a problem? Please describe.**
I happened to find out the macro `lazy-cat` is not defined in babashka. On the other hand, the macro `lazy-seq` is.

**Describe the solution you'd like**
Understand the macro is not widely used. Still, it would be nice to have it since it is part of the clojure.core.

**Additional context**
The bb version is: v0.2.1

**Comment by borkdude** [comment]
@randomizedthinking Will add to sci. Workaround for now:

``` 
(ns patch
  (:refer-clojure :exclude [lazy-cat]))

(defmacro lazy-cat
  "Expands to code which yields a lazy sequence of the concatenation
  of the supplied colls.  Each coll expr is not evaluated until it is
  needed. 
  (lazy-cat xs ys zs) === (concat (lazy-seq xs) (lazy-seq ys) (lazy-seq zs))"
  {:added "1.0"}
  [& colls]
  `(concat ~@(map #(list `lazy-seq %) colls)))

(intern 'clojure.core 'lazy-cat @#'lazy-cat)
(alter-meta! #'clojure.core/lazy-cat assoc :macro true)

(ns my-program)

(lazy-cat [1 2 3] [4 5 6])
```
