### ISSUE TITLE
System/exit throws exception

### ISSUE THREAD

**Issue by eigenhombre** [borkdude/babashka#606]
**v0.2.2**
**Mac Catalina**
**(System/exit 0) doesn't, but throws**
**repro**

    $ bb
    Babashka v0.2.2 REPL.
    Use :repl/quit or :repl/exit to quit the REPL.
    Clojure rocks, Bash reaches.
    user=> (System/exit 0)
    clojure.lang.ExceptionInfo [at <repl>:1:1]
    user=>

**expected behavior**
I want this to exit, and if I provide -1 as the exit code, for the Babashka process to return -1 to the calling shell, so I can use that code per standard Unix process semantics.

**Comment by borkdude** [comment]
Thanks. Note that this error only happens in a bb REPL. In a script `(System/exit 1)` works ok.

**Comment by borkdude** [comment]
Fixed on master.
