### ISSUE TITLE
clojure.pprint/print-table does not output to REPL (IntelliJ/Cursive)

### ISSUE THREAD

**Issue by MrGung** [borkdude/babashka#611]
**version**

0.2.1

**platform**

Windows - IntelliJ/Cursive

**problem**

Evaluating `clojure.pprint/print-table` the result is printed in the server-window of babashka (`bb --socket-repl 1666`). Whereas `pprint` prints to the REPL in IntelliJ.

**repro**

-

**expected behavior**

Both - pprint and print-table should print to the IntelliJ-REPL.

**Comment by borkdude** [comment]
@MrGung Can you please try with the newest bb?

**Comment by MrGung** [comment]
Unchanged.

**Comment by borkdude** [comment]
@MrGung I think I have a repro of the problem:

``` 
user=> (with-out-str (clojure.pprint/print-table [{:a 1} {:a 2}]))

| :a |
|----|
|  1 |
|  2 |
""
```

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/babashka/commit/b5f65e10a617720d68d9208e51646bf7017e3f07.
You can download a new binary by navigating to the builds of that commit for testing.

**Comment by MrGung** [comment]
Right -` with-out-str` also did not work.

I couldn't find an artifact for windows...?

**Comment by borkdude** [comment]
@MrGung Navigate to Appveyor for that: https://ci.appveyor.com/project/borkdude/babashka/builds/35686982

**Comment by MrGung** [comment]
Works! Output is now displayed in REPL. 

Thanks!
