### ISSUE TITLE
Difference from other implementations: can't call a symbol literal

### ISSUE THREAD

**Issue by Zabolekar** [borkdude/babashka#622]
**version**

0.2.3

**platform**

x86_64 GNU/Linux

**problem**

 `('a {'a 1})` evaluates to `1` in JVM Clojure, Clojurescript, Joker and Clojerl, but throws an exception in Babashka.

**actual behavior**

```
user=> ('a {'a 1})
java.lang.IllegalArgumentException: No matching clause: a [at <repl>:1:1]
```

**expected behavior**

```
user=> ('a {'a 1})
1
```

**workaround**

Saving the key to a variable and not using it directly as a literal. `(let [a 'a] (a {'a 1}))` evaluates to `1`, as expected.

**Comment by borkdude** [comment]
@Zabolekar Thanks! Definitely a bug.

Another workaround:

```
((symbol "a") {'a 1}) ;;=> 1
```

**Comment by borkdude** [comment]
@Zabolekar Should be fixed with https://github.com/borkdude/sci/commit/72c85bb8face7cb04496a1257362f2f487811f46 and https://github.com/borkdude/babashka/commit/c2fe136744b849e816d95692d1e66d55757f99bd. You can find a binary in the builds when they're finished.
