### ISSUE TITLE
Expose pprint/simple-dispatch

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#627]
@lvh Oh I see. That namespace uses `pp/simple-dispatch` which is currently not exposed in bb. Let's make a different issue for that and fix it.

_Originally posted by @borkdude in https://github.com/borkdude/babashka/issues/47#issuecomment-720123319_

**Comment by borkdude** [comment]
@lvh Added `simple-dispatch` to bb master. I took a look at `io/aviso/exception.clj` and apart from the missing class `java.lang.StackTraceElement` (which can be fixed) I ran into this dependency on a clojure `Compiler` internal:

https://github.com/AvisoNovate/pretty/blob/44d8574203c50dd79b6d4cf02b5f8aa905106f11/src/io/aviso/exception.clj#L65

**Comment by lvh** [comment]
Ah, crud. Thanks for looking into it!
