### ISSUE TITLE
Add sha-words to project page

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#629]
https://github.com/ordnungswidrig/sha-words

``` clojure
$ bb -cp src -m sha-words.main --uberjar sha-words.jar
$ bb sha-words.jar b67d6eafeae1d5a424a609864fad10665453afa5
packing-yesterday-sugar-cup-awkward
```

Make uberscript:

``` shell
$ bb -cp src -m sha-words.main --uberscript ~/Dropbox/bin/sha-words.clj
# prepend shebang
$ bb -e '(spit "/Users/borkdude/Dropbox/bin/sha-words.clj" (str "#!/usr/bin/env bb\n\n" (slurp "/Users/borkdude/Dropbox/bin/sha-words.clj")))'
$ chmod +x ~/Dropbox/bin/sha-words.clj
```

Win!
``` shel
$ sha-words.clj b67d6eafeae1d5a424a609864fad10665453afa5
packing-yesterday-sugar-cup-awkward
```

**Comment by brandonbloom** [comment]
I was surprised to discover that uberscript didn't prepend a shebang line for me. Then I stumbled across this, where you have to do it manually. Another spelling (in plain bash) that I came up with: `cat <(echo "#!/usr/bin/env bb") $script | sponge $script`

**Comment by borkdude** [comment]
> I was surprised to discover that uberscript didn't prepend a shebang line for me.

This is because not all systems understand shebangs, like Windows. bb is a cross-platform tool so you're responsible to add the shebang yourself.

**Comment by brandonbloom** [comment]
That's a good point, though I think it would still make sense to include it if it can safely be ignored on Windows. Or, at the very least, provide a command line option to uberscript to prepend something so that every Unix build script doesn't need to do the sponge dance.

**Comment by borkdude** [comment]
>  it if it can safely be ignored on Windows

I don't think it can

Yes, sure we can add more options but perhaps shebangs aren't universal among bash, zsh, macOS, and whatever, so I've decided not to take on that complexity and leave that up to some scripting.

**Comment by brandonbloom** [comment]
For an option, I wasn't suggesting adding a shebang automatically, rather I was suggesting `--preamble='#!/whatever/you/want` and then doing `(println preamble)`.  But fair enough, there are a dozen+ ways to add a prefix to a file with scripting.
