### ISSUE TITLE
:or in destructuring broken for false case

### ISSUE THREAD

**Issue by theonlysinjin** [borkdude/babashka#632]
babashka v0.2.3
Distro: Ubuntu 20.10

When using `false` as a parameter in `:or`, it returns `nil` instead of `false`.

Problem Case:
`(let [{:keys [public]
       :or {public false}}
      {:a 1}]
  public)
=> nil`

It works with other data types, e.g.
`(let [{:keys [public]
       :or {public "bob"}}
      {:a 1}]
  public)
=> "bob"`

Expected behaviour, to return `false` instead of `nil`
`(let [{:keys [public]
       :or {public false}}
      {:a 1}]
  public)
=> false`

**Comment by borkdude** [comment]
Could be a bug here: 

https://github.com/borkdude/sci/blob/971614de14a6fd00e6991d1afd6c0ce9fbda104c/src/sci/impl/destructure.cljc#L99

Compare:
https://github.com/clojure/clojure/blob/7baa5b2f79f05c56a04e1d5c90129972cd962df3/src/clj/clojure/core.clj#L4465

and

https://github.com/clojure/clojurescript/blob/5e88d3383e0f950c4de410d3d6ee11769f3714f4/src/main/clojure/cljs/core.cljc#L701

**Comment by theonlysinjin** [comment]
Subtle!

**Comment by borkdude** [comment]
Fixed https://github.com/borkdude/babashka/commit/ae0241be7d1ec3e1e1ae0146624b44d6d5947a0b. New bb can be found in the builds.
