### ISSUE TITLE
babashka.crypto / hmac

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#656]
Currently you can create hmac with openssl. But maybe adding java crypto for this might be better.

``` clojure
(defn sign-with-string [key msg]
  (-> (sh "openssl" "dgst" "-sha256" "-mac" "hmac" "-macopt" (str "key:" key) :in msg)
      :out
      str/trim))
(defn sign-with-hex [key msg]
    (-> (sh "openssl" "dgst" "-sha256" "-mac" "hmac" "-macopt" (str "hexkey:" key) :in msg)
        :out
        str/trim))
```

You can also shell out to `shasum`.

We could also make a small babashka.crypto namespace (or some other name) with util functions.

Prior art: 
- https://github.com/funcool/buddy-core/blob/master/src/buddy/core/crypto.clj
- https://candid82.github.io/joker/joker.crypto.html

I'd rather not depend on / expose buddy directly since that would maybe bloat bb too much with stuff which isn't used that much.

Alternative: buddy pod. See #690

**Comment by tjefferson08** [comment]
Thanks for keeping track of things, @borkdude 

Here's the java code that I wanted to be available from `java.crypto` when I cooked up the idea to shell out to openssl:

```java
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

public class HMAC {
  static public byte[] calcHmacSha256(byte[] secretKey, byte[] message) {
    byte[] hmacSha256 = null;
    try {
      Mac mac = Mac.getInstance("HmacSHA256");
      SecretKeySpec secretKeySpec = new SecretKeySpec(secretKey, "HmacSHA256");
      mac.init(secretKeySpec);
      hmacSha256 = mac.doFinal(message);
    } catch (Exception e) {
      throw new RuntimeException("Failed to calculate hmac-sha256", e);
    }
    return hmacSha256;
  }
}
```
(from [this site](https://sorenpoulsen.com/calculate-hmac-sha256-with-java))

Disclaimer: I don't know anything about crypto

**Comment by Heliosmaster** [comment]
From a project where i did something similar, i used these classes:
```
 (:import (javax.crypto.spec SecretKeySpec)
           (javax.crypto Mac)
           (org.apache.commons.codec.digest DigestUtils))
```
and this code for hmac-256

```(defn hmac-sha256 [key string]
  "Returns the signature of a string with a given
    key, using a SHA-256 HMAC."
  (let [mac (Mac/getInstance "HMACSHA256")
        secretKey (SecretKeySpec. key (.getAlgorithm mac))]
    (-> (doto mac
          (.init secretKey)
          (.update (.getBytes string)))
        .doFinal)))
```

**Comment by justone** [comment]
Here's another use-case I have for crypto. We have an API that's protected by a shared secret, and we use HMAC for authentication. Here's the distilled code I use on the JVM:

```clojure
(require '[buddy.core.codecs :as codecs])
(require '[buddy.core.mac :as mac])
(require '[buddy.core.nonce :as nonce])
(require '[clojure.string :as string])

(def hash-algorithm :hmac+sha256)
(def secret (nonce/random-bytes 64))

(let [timestamp (System/currentTimeMillis)
      nonce (nonce/random-bytes 64)
      nonce-hex (codecs/bytes->hex nonce)
      payload (pr-str {:nonce nonce-hex :timestamp timestamp})
      signature (codecs/bytes->hex (mac/hash payload {:alg hash-algorithm :key secret}))]
  (string/join "-" [nonce-hex timestamp signature]))
```

I'm going to attempt to replicate this with shelling out to openssl, will post again if I'm successful.

**Comment by borkdude** [comment]
I've started work on a buddy pod: https://github.com/babashka/pod-babashka-buddy

The idea is that this pod will be easily installable via https://github.com/babashka/pod-registry (also see https://book.babashka.org/master.html#_pod_registry).

Currently the three pod functions return a base64 encoded string instead of a byte array. This is a result of pods having to serialize the bytes. I could unwrap the base64 string in babashka into a byte array again (transparently to the user), but I'm not sure if that makes sense.

Feedback welcome.

**Comment by borkdude** [comment]
Never mind, I went with transit and this can deserialize bytes without even thinking about it (and hopefully does it efficiently).

The @justone example works:

![Screenshot 2020-12-27 at 20 04 26](https://user-images.githubusercontent.com/284934/103177931-d74a9300-487e-11eb-81c6-a6d83d2e3c40.png)

**Comment by justone** [comment]
@borkdude I just tried it out and it works great! This is fantastic! Thanks for getting this working.

**Comment by borkdude** [comment]
The buddy pod can now be downloaded via the pod-registry in bb 0.2.6:

<img width="653" alt="Screenshot 2020-12-29 at 16 11 12" src="https://user-images.githubusercontent.com/284934/103293738-bbff9500-49f0-11eb-9d9f-7183b41a18ab.png">

Buddy gives access to a wide range of crypto stuff, so there you go!

**Comment by tjefferson08** [comment]
thanks @borkdude ❤️

**Comment by justone** [comment]
Awesome. Thank you @borkdude !!

**Comment by borkdude** [comment]
FYI, a PR just got merged that adds some Hmac support to babashka, so in the next release you might not need the pod for some things.

https://github.com/babashka/babashka/commit/5940b95cd2417da7087400746228acf1e66ecad3
