### ISSUE TITLE
babashka.json

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#657]
This namespace will wrap cheshire.core and will allow us to migrate to other JSON libs in the future (for speed or binary size). The cheshire.core namespace will be deprecated for a few months and then be phased out. We will offer a JVM version of this facade as well, so people can migrate their bb scripts to the JVM if they want.

**Comment by eigenhombre** [comment]
I've had good experience w/ Cheshire over the years - just out of curiosity, is its compiled binary overly large?

**Comment by borkdude** [comment]
It's actually pretty small I think.I would eventually like to have the freedom to move to a different implementation (e.g. jsonista, or otherwise) and remove the json-smile / cbor stuff that probably nobody is using. The latter would free up some space. I haven't measured how much. I will do that now.

**Comment by eigenhombre** [comment]
Nice to have implementation independence, for sure.

**Comment by borkdude** [comment]
Unmapping the cheshire smile functions saves about `184320` bytes in the binary.
I might just do that as a first step (and I will add it back on request, if people really depended on it).

**Comment by borkdude** [comment]
@eigenhombre On the other hand, it's nice to have some recognisable APIs that are used a lot, like cheshire. And it's working well. So I might not pursue this issue, it's just something that crossed my mind a couple of times when I see alternatives like clojure.data.json / jsonista. Probably going forward I will only add babashka.* namespaces to not get dependent on existing libraries (which may go out of fashion or unmaintained). I will keep the clojure.* namespaces for sure. I have some reservations about keeping http-kit as is, which you can read about here: https://github.com/borkdude/babashka/wiki/HTTP-client-and-server-considerations

**Comment by borkdude** [comment]
I'm declining this idea (for now) since familiarity is one of the pillars of bb and cheshire.core is a familiar API for the clojure community.
