### ISSUE TITLE
Call an namespaced script, that does not have a -main

### ISSUE THREAD

**Issue by MrGung** [borkdude/babashka#685]
**Is your feature request related to a problem? Please describe.**
I have some scripts in a source-repo that's in the "classpath". These scripts don't have a -main-Method. They should be executed on evaluation.

I wouldn't want to add the path to the script in the invokation - I'd rather call the script by its namespace.

That kinda works, but gives an exception at the end of the execution because -main is not found.

**Describe the solution you'd like**
Either -m does not throw an exception when no -main is found. Or another CLI-switch is provided.

**Describe alternatives you've considered**
I could live with the exception. Or I may add the path to the script when invoking it. But that would add another dependency which I don't like.

**Additional context**
-

**Comment by borkdude** [comment]
@MrGung Why don't you add a -main function to each of the scripts you want to invoke with `-m`?

Additional info that could be relevant:

You can dynamically add the classpath to a script with `babashka.classpath/add-classpath`.

See: https://book.babashka.org/#babashka_classpath

If you are using dependencies from maven or git, you can use https://book.babashka.org/#babashkadeps to resolve them dynamically.

The clojure CLI recently added an option to execute an arbitrary function on the classpath:

```
clojure -X foo.bar/baz :foo 1 :bar 2
```

Would something like this also make sense in your context?

I'm also considering a `babashka.edn` file that contains default dependencies and paths for a multi-file project in this issue:

https://github.com/borkdude/babashka/issues/680

**Comment by MrGung** [comment]
Thanks. An empty `main` does the trick.

I could even use the pattern you describe in the docs:

```
(defn -main [& args]
  (do))

(if (= *file* (System/getProperty "babashka.file")
      (-main *command-line-args*)))
```
