### ISSUE TITLE
Termux build

### ISSUE THREAD

**Issue by tom-adsfund** [borkdude/babashka#71]
This project is extremely cool, exactly what I've wanted.

Any chance to build for Termux (Android)?

**Comment by borkdude** [comment]
@tom-adsfund I'm not an Android user myself, but if someone has experience with this and wants to do a PR, I'm open to it.

**Comment by borkdude** [comment]
Going to close this for now. If there will be any volunteers I'm happy to reopen it.

**Comment by borkdude** [comment]
Some people have reported that Termux works for them [here](https://github.com/babashka/babashka/issues/241).

**Comment by rene-descartes2021** [comment]
That's a long discussion to read through, most all involving a proot or raspberry PI, so I'll point out this [post](https://github.com/babashka/babashka/discussions/1392#discussioncomment-12181334) which says babashka works on Termux with glibc-runner, no proot involved.

In terms of building a babashka release for Android (for use in Termux), I looked at GraalVM for Android support: in their issues they advised using [Gluon Substrate](https://github.com/gluonhq/substrate) to provide compiled natives for Android and other platforms. Something to consider if the glibc-runner solution is not satisfactory... looks like glibc-runner needs 0.5 GB of dependencies.

**Comment by tom-adsfund** [comment]
@rene-descartes2021 Perfect, just got it working.

For anyone else, just make sure you install everything as in the post, and if you have bb in the current dir, you need to use "./bb" with "grun".

**Comment by sogaiu** [comment]
FWIW, at least in my case some of the additional info in the "More details on the issue" section of the [comment rene-descartes2021 linked to](https://github.com/babashka/babashka/discussions/1392#discussioncomment-12181334) was needed and there appears to be some limitations of what one can do once `unset LD_PRELOAD` is invoked (e.g. `clj` and `clojure` don't start here from a shell where that invocation has been performed).
