### ISSUE TITLE
Different behavior via socket repl

### ISSUE THREAD

**Issue by sogaiu** [borkdude/babashka#81]
**version**

945b7685f14fede266527c018dce74f65bc53380

**platform**

Manjaro Linux

**problem**

Output differed between execution at the command line compared to socket repl.

**repro**

command line:

```
./bb "(defmacro bindings [] (mapv #(list 'quote %) (keys &env))) (defn bar [x] (println (bindings)) x) (bar 1)"
```

yielded the output:

```
[x]
1
```

via the socket repl:

```
bb=> (defmacro bindings [] (mapv #(list 'quote %) (keys &env))) (defn bar [x] (println (bindings)) x) (bar 1)
```

yielded the output:

```
[%1]
1
```

**expected behavior**

Expected to see [x], not [%1]

**Comment by borkdude** [comment]
Hopefully fixed in the https://github.com/borkdude/babashka/tree/fix-socket-repl-env branch. If you could test it, then I'll merge to master.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/babashka/commit/85aeaa354b911be03c33812c717a8d19ecf0fa52.

**Comment by sogaiu** [comment]
Thanks!
